# -*- coding: utf-8 -*-
"""Hinglish/English→Devanagari phrase dictionary for the marriage (shaadi) funnel.
Keys are exact source text-runs as rendered (whitespace-collapsed); values are
conversational Devanagari (respectful आप). See shaadi_hi.py for the engine."""

HI_DATA = {
    "\"It didn't promise a date, which is exactly why I trusted it. It said which years look stronger and why — matched what a family astrologer told me, minus the ₹2000 fee.\"": "\"इसने कोई तारीख का वादा नहीं किया, और यही वजह है कि मैंने इस पर भरोसा किया। इसने बताया कि कौन से साल ज़्यादा मज़बूत लगते हैं और क्यों — बिल्कुल वही जो एक फैमिली ज्योतिषी ने मुझे कहा था, बस ₹2000 की फीस के बिना।\"",
    "\"Liked that it showed the reasoning — which dasha, which house. Took it to a pandit ji we trust and he said the logic was sound.\"": "\"अच्छा लगा कि इसमें वजह भी बताई गई — कौन सी दशा, कौन सा भाव। हमने इसे अपने भरोसे के पंडित जी को दिखाया, और उन्होंने कहा कि तर्क सही है।\"",
    "\"My mum had been asking 'shaadi kab hogi' for two years. The report gave an actual window with reasons — I showed it to her and even she calmed down.\"": "\"मेरी माँ दो साल से पूछ रही थीं 'शादी कब होगी'। रिपोर्ट ने वजहों के साथ एक असली विंडो दी — मैंने उन्हें दिखाई और वो भी शांत हो गईं।\"",
    "\"The Manglik bit had worried me for years. It explained the cancellation clearly instead of just scaring me. Honestly a relief.\"": "\"मांगलिक वाली बात सालों से मुझे परेशान कर रही थी। इसने डराने के बजाय कैंसलेशन को साफ़-साफ़ समझाया। सच में राहत मिली।\"",
    "\"Was low-key panicking after 29 with everyone getting married. Seeing the actual timing windows made me stop spiralling and just breathe.\"": "\"29 के बाद सबकी शादियाँ होते देख अंदर ही अंदर घबरा रही थी। असली टाइमिंग विंडो देखकर मैंने उलझना बंद किया और बस चैन की साँस ली।\"",
    ". Iska matlab delay ka pressure, denial nahi — Shani ke period mein bani shaadiyan sabse tikau maani jaati hain. Windows upar isi ko account karke grade hue hain.": "। इसका मतलब देरी का दबाव है, इनकार नहीं — शनि के दौर में बनी शादियाँ सबसे टिकाऊ मानी जाती हैं। ऊपर दी गई विंडो इसी को ध्यान में रखकर ग्रेड की गई हैं।",
    ". Tradition mein cancelled manglik ko manglik nahi mana jaata — matching mein isse issue nahi banna chahiye.": "। परंपरा में रद्द हुए मांगलिक दोष को मांगलिक नहीं माना जाता — मिलान में इससे कोई दिक्कत नहीं बननी चाहिए।",
    "2 min": "2 मिनट",
    "2 minutes": "2 मिनट",
    "2024–25 mein rishte kyun nahi bane? Chart mein jawab hai.": "2024–25 में रिश्ते क्यों नहीं बने? जवाब आपकी कुंडली में है।",
    "3 aur sach": "3 और सच",
    "7th house": "7वाँ भाव",
    "7th house khaali hai": "7वाँ भाव खाली है",
    "7th house kya kehta hai — nature, arranged ya self-driven yog.": "7वाँ भाव क्या कहता है — स्वभाव, अरेंज्ड या ख़ुद से बनने वाला योग।",
    "7th lord": "7वें भाव का स्वामी",
    "= vargottama": "= वर्गोत्तम",
    "AD is Saturn/Ketu with no 7th connection": "AD शनि/केतु है, 7वें भाव से कोई संबंध नहीं",
    "AD lord conjunct the 7th lord": "अंतर्दशा का स्वामी 7वें भाव के स्वामी के साथ युति में",
    "AD lord debilitated or combust": "AD का स्वामी नीच या अस्त है",
    "AD lord is Venus/Jupiter (marriage karaka)": "अंतर्दशा (AD) का स्वामी शुक्र/गुरु है (मैरिज कारक)",
    "AD lord is the darakaraka": "अंतर्दशा का स्वामी दारकारक है",
    "AD lord occupies or aspects the 7th house": "अंतर्दशा का स्वामी 7वें भाव में हो या उस पर दृष्टि रखे",
    "AXTROSHASTRA": "AXTROSHASTRA",
    "Aap manglik nahi hain ✅": "आप मांगलिक नहीं हैं ✅",
    "Aap pyaar kaise karte hain — chart ke hisaab se": "आप प्यार कैसे करते हैं — कुंडली के हिसाब से",
    "Aapka Venus": "आपका शुक्र",
    "Aapka chart — marriage lens se": "आपकी कुंडली — शादी के नज़रिए से",
    "Aapka jawab — ek nazar mein": "आपका जवाब — एक नज़र में",
    "Aapka mann aur emotional nature. Aapki dasha timeline isi Moon-nakshatra se chalti hai — yahi timing ka engine hai.": "आपका मन और भावनात्मक स्वभाव। आपकी दशा की समयरेखा इसी चंद्र-नक्षत्र से चलती है — यही टाइमिंग का इंजन है।",
    "Aapka pattern": "आपका पैटर्न",
    "Aapka poora chart — verify kijiye": "आपकी पूरी कुंडली — जाँच लीजिए",
    "Aapke": "आपके",
    "Aapke 7th house mein baithe graha:": "आपके 7वें भाव में बैठे ग्रह:",
    "Aapke 7th lord": "आपके 7वें भाव का स्वामी",
    "Aapke chart mein 5th–7th connection hai — love-marriage ya self-driven rishtey ka yog. Arranged setup mein bhi pasand aapki hi chalegi.": "आपकी कुंडली में 5वें–7वें भाव का संबंध है — प्रेम-विवाह या अपनी पसंद के रिश्ते का योग। अरेंज सेटअप में भी चलेगी आपकी ही पसंद।",
    "Aapke marriage windows": "आपकी शादी की विंडो",
    "Aapke pichhle periods ka chart-analysis. Agar rishtey aaye par bane nahi, ya bilkul shaant raha — yahan uski wajah dikhegi:": "आपके पिछले दौर का कुंडली-विश्लेषण। अगर रिश्ते आए पर बने नहीं, या बिल्कुल शांत रहा — यहाँ उसकी वजह दिखेगी:",
    "Aapke top window ka scorecard": "आपकी टॉप विंडो का स्कोरकार्ड",
    "Aapki": "आपकी",
    "Aapki kundli abhi compute ho rahi hai — templates nahi.": "आपकी कुंडली अभी गणना हो रही है — कोई टेम्पलेट नहीं।",
    "Aapki personality aur poore chart ka base — har bhaav isi se gina jaata hai.": "आपके व्यक्तित्व और पूरी कुंडली का आधार — हर भाव इसी से गिना जाता है।",
    "Ab karna kya hai": "अब करना क्या है",
    "Ab tak kya hua — aur kyun": "अब तक क्या हुआ — और क्यों",
    "Abhi kaunsi dasha chal rahi hai. Windows isi timeline par bante hain — isliye yeh sabse relevant.": "अभी कौन-सी दशा चल रही है। विंडो इसी टाइमलाइन पर बनती हैं — इसलिए यह सबसे ज़रूरी है।",
    "About Us": "हमारे बारे में",
    "Action plan": "कार्य योजना",
    "Agar pichhle saalon mein baat banti-banti reh gayi ho — chart mein aksar uski wajah dikh jaati hai. Yeh aapki kami nahi thi; timing thi.": "अगर पिछले सालों में बात बनते-बनते रह गई हो — कुंडली में अक्सर उसकी वजह दिख जाती है। यह आपकी कमी नहीं थी; यह समय की बात थी।",
    "Agle 3 saal — ek nazar mein": "अगले 3 साल — एक नज़र में",
    "Aksar poochhe gaye sawaal": "अक्सर पूछे गए सवाल",
    "Ambitious, focused, dual-natured — victory is your vocabulary": "महत्वाकांक्षी, एकाग्र, दोहरे स्वभाव वाले — जीत आपकी भाषा है",
    "Ambitious, focused, dual-natured — victory is your vocabulary.": "महत्वाकांक्षी, एकाग्र, दोहरे स्वभाव वाले — जीत आपकी भाषा है।",
    "Antardasha lord is Venus/Jupiter (marriage karaka)": "अंतर्दशा का स्वामी शुक्र/गुरु है (मैरिज कारक)",
    "Antardasha lord is the 7th lord": "अंतर्दशा का स्वामी ही 7वें भाव का स्वामी है",
    "Apni details bhariye — jawab 2 minute mein.": "अपनी जानकारी भरिए — जवाब 2 मिनट में।",
    "Approximate time": "अनुमानित समय",
    "Axtroshastra": "Axtroshastra",
    "Back of the bed": "खाट का पिछला भाग",
    "Balanced, dependable, contract-honouring — your word is your bond": "संतुलित, भरोसेमंद, वादे निभाने वाले — आपकी ज़बान ही आपका वचन है",
    "Balanced, dependable, contract-honouring — your word is your bond.": "संतुलित, भरोसेमंद, वचन निभाने वाले — आपकी बात ही आपका वादा है।",
    "Banaya IIT–IIM engineers ne.": "बनाया IIT–IIM इंजीनियरों ने।",
    "Bhaav": "भाव",
    "Bhaav (house) lagna se gina gaya hai": "भाव (house) लग्न से गिना गया है",
    "Bilkul nahi pata": "बिल्कुल नहीं पता",
    "Birth details sirf aapki report ke liye use hoti hain. No spam calls — hum aapka number kisi astrologer ko nahi bechte. (Yeh common industry practice hai; hum nahi karte.)": "जन्म-विवरण सिर्फ़ आपकी रिपोर्ट के लिए इस्तेमाल होते हैं। कोई स्पैम कॉल नहीं — हम आपका नंबर किसी ज्योतिषी को नहीं बेचते। (यह इंडस्ट्री की आम बात है; हम ऐसा नहीं करते।)",
    "Birth time approximate tha?": "जन्म समय अनुमानित था?",
    "Birth time exact nahi pata?": "जन्म का सटीक समय नहीं पता?",
    "Birth time exactly nahi pata?": "जन्म का सही समय नहीं पता?",
    "Birth time problem?": "जन्म समय की दिक्कत?",
    "Blog": "ब्लॉग",
    "Blue Sapphire (Neelam) — only after expert trial, if Saturn is well-placed": "Blue Sapphire (नीलम) — सिर्फ़ जानकार की देखरेख में परखने के बाद, अगर शनि अच्छी स्थिति में हो",
    "Blue Sapphire (Neelam) — only after expert trial, if Saturn is well-placed — kisi qualified jeweller/astrologer se trial ke baad hi.": "नीलम — सिर्फ़ किसी जानकार की देखरेख में ट्रायल के बाद, अगर शनि अच्छी स्थिति में हो — किसी योग्य जौहरी/ज्योतिषी से ट्रायल के बाद ही।",
    "Bow and quiver": "धनुष और तरकश",
    "Budh, Guru — yeh partnership ke rang ko sabse seedha shape dete hain:": "बुध, गुरु — ये आपके रिश्ते के रंग को सबसे सीधे आकार देते हैं:",
    "Budh, Shani — yeh partnership ke rang ko sabse seedha shape dete hain:": "बुध, शनि — ये आपके रिश्ते के रंग को सबसे सीधे तरीके से आकार देते हैं:",
    "Budh, Shani, Ketu — yeh partnership ke rang ko sabse seedha shape dete hain:": "बुध, शनि, केतु — ये साथ के रंग को सबसे सीधे आकार देते हैं:",
    "Budh, Shukra — yeh partnership ke rang ko sabse seedha shape dete hain:": "बुध, शुक्र — ये साझेदारी के रंग को सबसे सीधे आकार देते हैं:",
    "Budhvar (Wednesday)": "बुधवार",
    "Building ≥ 3. Koi astrologer chaahe toh in rules ko apne haath se verify kar sakta hai — kyunki yeh judgement nahi, calculation hai.": "निर्माणाधीन ≥ 3. कोई ज्योतिषी चाहे तो इन नियमों को अपने हाथ से जाँच सकता है — क्योंकि यह अटकल नहीं, गणना है।",
    "Built by": "बनाया",
    "Bundle of roots": "जड़ों का गुच्छा",
    "Calculations computer karta hai — isliye unbiased hai. Rules wahi classical Vedic principles hain (dasha + transit) jo ek achha astrologer use karta hai. Difference: humara system thakta nahi, bhoolta nahi, aur mood se jawab nahi badalta.": "गणना कंप्यूटर करता है — इसलिए इसमें कोई पक्षपात नहीं है। नियम वही क्लासिकल वैदिक सिद्धांत हैं (दशा + गोचर) जो एक अच्छा ज्योतिषी इस्तेमाल करता है। फर्क बस इतना: हमारा सिस्टम थकता नहीं, भूलता नहीं, और मूड के हिसाब से जवाब नहीं बदलता।",
    "Cancelled (effectively no)": "रद्द (यानी असल में नहीं)",
    "Cards": "कार्ड",
    "Career Timing Report — same precision, ₹299 for report holders.": "करियर टाइमिंग रिपोर्ट — वही सटीकता, रिपोर्ट धारकों के लिए ₹299।",
    "Chandra, Ketu — yeh partnership ke rang ko sabse seedha shape dete hain:": "चंद्र, केतु — ये साझेदारी के रंग को सबसे सीधे आकार देते हैं:",
    "Chandra, Mangal — yeh partnership ke rang ko sabse seedha shape dete hain:": "चंद्र, मंगल — ये साझेदारी के रंग को सबसे सीधे आकार देते हैं:",
    "Chandra, Mangal, Shani — yeh partnership ke rang ko sabse seedha shape dete hain:": "चंद्र, मंगल, शनि — ये आपके रिश्ते के रंग को सबसे सीधे आकार देते हैं:",
    "Chandra, Mangal, Shukra — yeh partnership ke rang ko sabse seedha shape dete hain:": "चंद्र, मंगल, शुक्र — ये पार्टनरशिप के रंग को सबसे सीधे तौर पर आकार देते हैं:",
    "Chandra, Rahu — yeh partnership ke rang ko sabse seedha shape dete hain:": "चंद्र, राहु — ये साझेदारी के रंग को सबसे सीधे आकार देते हैं:",
    "Chandra, Shukra — yeh partnership ke rang ko sabse seedha shape dete hain:": "चंद्र, शुक्र — ये आपके रिश्ते के रंग को सबसे सीधे आकार देते हैं:",
    "Chariot / ox-cart": "रथ / बैलगाड़ी",
    "Charismatic, artistic, form-loving — you shape beauty from chaos": "आकर्षक, कलात्मक, सुंदरता के प्रेमी — आप बिखराव से भी सुंदरता गढ़ लेते हैं",
    "Charismatic, artistic, form-loving — you shape beauty from chaos.": "आकर्षक, कलात्मक, सौंदर्य-प्रेमी — आप अफ़रा-तफ़री में से भी सुंदरता गढ़ लेते हैं।",
    "Chart ka jhukaav traditional/arranged path ki taraf hai — introductions aur family networks se hi strong yog banta hai.": "कुंडली का झुकाव पारंपरिक/अरेंज्ड रास्ते की तरफ है — परिचय और पारिवारिक नेटवर्क से ही मज़बूत योग बनता है।",
    "Chart snapshot": "कुंडली का स्नैपशॉट",
    "Check FREE": "मुफ़्त में जाँचिए",
    "Coiled serpent": "कुंडली मारे साँप",
    "Computational Vedic Astrology": "कंप्यूटेशनल वैदिक ज्योतिष",
    "Current period": "मौजूदा अवधि",
    "D9": "D9",
    "D9 7th house": "D9 का 7वाँ भाव",
    "D9 7th lord": "D9 का 7वें भाव का स्वामी",
    "D9 chart ·": "D9 कुंडली ·",
    "D9 lagna": "D9 लग्न",
    "D9 mein koi strong plus ya minus signal nahi — neutral promise, timing D1 se aati hai.": "D9 में कोई मज़बूत प्लस या माइनस संकेत नहीं — सामान्य प्रॉमिस, समय D1 से आता है।",
    "D9 promise ki baat hai, timing ki nahi — timing upar ke windows batate hain. Dono milkar poori tasveer dete hain.": "D9 वादे की बात है, समय की नहीं — समय तो ऊपर की विंडो बताती हैं। दोनों मिलकर पूरी तस्वीर देते हैं।",
    "Darakaraka": "दारकारक",
    "Date of birth": "जन्म तिथि",
    "Deep-digging, truth-seeking, uprooting — surface answers never satisfy you": "गहराई में खोदने वाले, सच्चाई की तलाश करने वाले, जड़ तक जाने वाले — ऊपरी जवाब आपको कभी संतुष्ट नहीं करते",
    "Deep-digging, truth-seeking, uprooting — surface answers never satisfy you.": "गहराई में जाने वाले, सच की खोज करने वाले, जड़ तक पहुँचने वाले — ऊपरी जवाब आपको कभी संतुष्ट नहीं करते।",
    "Deer's head": "हिरण का सिर",
    "Devoted, friendly, harmonising — you soften hard rooms": "समर्पित, दोस्ताना, तालमेल बिठाने वाले — आप तनाव भरे माहौल को नरम कर देते हैं",
    "Devoted, friendly, harmonising — you soften hard rooms.": "समर्पित, दोस्ताना, तालमेल बिठाने वाले — आप तनाव भरे माहौल को नरम कर देते हैं।",
    "Diamond/White Sapphire — only if Venus is well-placed": "हीरा/सफ़ेद पुखराज — केवल तभी जब शुक्र अच्छी स्थिति में हो",
    "Diamond/White Sapphire — only if Venus is well-placed — kisi qualified jeweller/astrologer se trial ke baad hi.": "हीरा/सफ़ेद पुखराज — सिर्फ़ तभी जब शुक्र अच्छी स्थिति में हो — किसी योग्य जौहरी/ज्योतिषी से परखने के बाद ही।",
    "Din (10 AM – 4 PM)": "दिन (10 AM – 4 PM)",
    "Disclaimer:": "अस्वीकरण:",
    "Download PDF": "PDF डाउनलोड करें",
    "Drum": "डमरू",
    "Ear / three footprints": "कान / तीन पदचिह्न",
    "Earring / umbrella": "कुंडल / छत्र",
    "Ek aur sawaal, usi chart se: career kab lift hoga?": "एक और सवाल, उसी कुंडली से: करियर कब उठान भरेगा?",
    "Elephant tusk / cot": "हाथी दाँत / खाट",
    "Elephant tusk / fan": "हाथी दाँत / पंखा",
    "Emerald (Panna) — only if Mercury is well-placed": "पन्ना (Emerald) — सिर्फ़ तभी जब बुध अच्छी स्थिति में हो",
    "Emerald (Panna) — only if Mercury is well-placed — kisi qualified jeweller/astrologer se trial ke baad hi.": "पन्ना (Emerald) — सिर्फ़ तभी जब बुध अच्छी स्थिति में हो — किसी योग्य ज्वेलर/ज्योतिषी से ट्रायल के बाद ही।",
    "Empty circle / 100 healers": "खाली वृत्त / 100 वैद्य",
    "Fast, healing, pioneering — you begin things others hesitate to start": "तेज़, उपचार करने वाले, अग्रणी — जिन कामों को शुरू करने में दूसरे झिझकते हैं, उन्हें आप शुरू करते हैं",
    "Fast, healing, pioneering — you begin things others hesitate to start.": "तेज़, चंगा करने वाले, अगुआई करने वाले — आप वो शुरुआत करते हैं जिन्हें शुरू करने में दूसरे हिचकिचाते हैं।",
    "Fish / drum": "मछली / मृदंग",
    "Flower / udder": "फूल / थन",
    "Free Chart Snapshot": "फ्री कुंडली स्नैपशॉट",
    "Free snapshot": "फ्री स्नैपशॉट",
    "Front of the bed": "खाट का अगला भाग",
    "Full Marriage Timing Report": "पूरी मैरिज टाइमिंग रिपोर्ट",
    "Full chart": "पूरी कुंडली",
    "Gemstone:": "रत्न:",
    "Generated 2026-07-28": "तैयार किया गया 2026-07-28",
    "Grade bands: Strong ≥ 8": "ग्रेड श्रेणियाँ: मज़बूत ≥ 8",
    "Graha": "ग्रह",
    "Guru, Rahu — yeh partnership ke rang ko sabse seedha shape dete hain:": "गुरु, राहु — ये आपके रिश्ते के रंग को सबसे सीधे आकार देते हैं:",
    "Guru, Shani — yeh partnership ke rang ko sabse seedha shape dete hain:": "गुरु, शनि — ये साथ के रंग को सबसे सीधे आकार देते हैं:",
    "Guruvar (Thursday)": "गुरुवार",
    "HAAN": "हाँ",
    "Haan. Approximate time ke saath hum windows nikaal sakte hain (thodi wider range ke saath), aur rectification option se time narrow bhi ho sakta hai.": "हाँ। अनुमानित समय के साथ भी हम विंडो निकाल सकते हैं (थोड़ी चौड़ी रेंज के साथ), और रेक्टिफ़िकेशन विकल्प से समय को और सटीक भी किया जा सकता है।",
    "Hamari specialty hai.": "यह हमारी ख़ासियत है।",
    "Hand": "हाथ",
    "Har window ka reason": "हर विंडो की वजह",
    "Har window ke card mein uske reasons diye hain — kaunsi dasha, kaunsa connection. Broad logic:": "हर विंडो के कार्ड में उसकी वजहें दी गई हैं — कौन-सी दशा, कौन-सा संबंध। मोटे तौर पर तर्क:",
    "Horse's head": "घोड़े का सिर",
    "Hum guarantee nahi karte. Hum probability batate hain.": "हम गारंटी नहीं देते। हम संभावना बताते हैं।",
    "Hum kuch chhupate nahi. Neeche aapke saare 9 grahon ki exact position hai — koi bhi astrologer ise apni panchang se milaa sakta hai. Yahi hamari transparency hai.": "हम कुछ नहीं छिपाते। नीचे आपके सभी 9 ग्रहों की सटीक स्थिति दी गई है — कोई भी ज्योतिषी इसे अपने पंचांग से मिला सकता है। यही हमारी पारदर्शिता है।",
    "IIT–IIM alumni": "IIT–IIM के पूर्व छात्र",
    "IIT–IIM alumni engineers jinhone classical Vedic rules ko software mein encode kiya. Hum astrologer nahi hain — isliye hamara system opinion nahi deta, sirf calculation.": "IIT–IIM के पूर्व छात्र इंजीनियर, जिन्होंने पारंपरिक वैदिक नियमों को सॉफ़्टवेयर में ढाल दिया। हम ज्योतिषी नहीं हैं — इसलिए हमारा सिस्टम राय नहीं देता, सिर्फ़ गणना करता है।",
    "In love you go to the root of everything; partners must survive your honesty to earn your depth": "प्रेम में आप हर चीज़ की जड़ तक जाते हैं; पार्टनर को आपकी गहराई पाने के लिए आपकी ईमानदारी को झेलना पड़ता है",
    "In love you go to the root of everything; partners must survive your honesty to earn your depth.": "प्यार में आप हर बात की जड़ तक जाते हैं; जो आपकी सच्चाई को झेल जाए, वही आपकी गहराई का हकदार बनता है।",
    "In love you move quickly and openly; you need a partner who can keep pace, not one who tests patience": "प्रेम में आप तेज़ी और खुलेपन से बढ़ते हैं; आपको ऐसा साथी चाहिए जो आपके साथ क़दम मिला सके, न कि जो सब्र की परीक्षा ले",
    "In love you move quickly and openly; you need a partner who can keep pace, not one who tests patience.": "प्यार में आप तेज़ी और खुलकर आगे बढ़ते हैं; आपको ऐसा साथी चाहिए जो आपकी रफ़्तार से चल सके, न कि जो आपके धैर्य की परीक्षा ले।",
    "Independent, adaptable, diplomatic — you move alone and gracefully": "स्वतंत्र, ढल जाने वाले, कूटनीतिक — आप अकेले और गरिमा के साथ चलते हैं",
    "Independent, adaptable, diplomatic — you move alone and gracefully.": "स्वतंत्र, ढल जाने वाले, कूटनीतिक — आप अकेले और सलीके से आगे बढ़ते हैं।",
    "Intense, creative, carrying — you hold and transform whatever you take on": "गहन, रचनात्मक, संभालने वाले — जो भी ज़िम्मा लेते हैं उसे थामते हैं और बदल देते हैं",
    "Intense, creative, carrying — you hold and transform whatever you take on.": "गहन, रचनात्मक, संभालने वाले — जो भी ज़िम्मा उठाते हैं उसे थामते और बदल देते हैं।",
    "Intense, transformative, fire-carrying — you burn and rebuild": "गहन, बदलाव लाने वाले, आग समेटे — आप जलते हैं और फिर से बनाते हैं",
    "Intense, transformative, fire-carrying — you burn and rebuild.": "गहरे, बदलाव लाने वाले, आग समेटे हुए — आप जलते हैं और फिर से खड़े होते हैं।",
    "Invincible-spirited, proud, purifying — you rise after every fall": "अजेय हौसले वाले, स्वाभिमानी, निखारने वाले — आप हर गिरावट के बाद फिर उठ खड़े होते हैं",
    "Invincible-spirited, proud, purifying — you rise after every fall.": "अजेय हौसले वाले, स्वाभिमानी, शुद्ध करने वाले — हर गिरावट के बाद आप फिर उठ खड़े होते हैं।",
    "Is chart mein koi graha vargottama nahi — normal hai, zyaadatar charts mein 0–2 hote hain.": "इस कुंडली में कोई ग्रह वर्गोत्तम नहीं है — यह सामान्य है, ज़्यादातर कुंडलियों में 0–2 ही होते हैं।",
    "Isliye calculation par bharosa hai, kismat-connection par nahi. We're not astrologers selling reassurance — we're engineers who encoded classical Vedic dasha–transit principles into software. So the answer comes from your chart, not from someone's mood that day.": "इसीलिए हमारा भरोसा गणना पर है, किसी किस्मत के कनेक्शन पर नहीं। हम भरोसा बेचने वाले ज्योतिषी नहीं हैं — हम इंजीनियर हैं जिन्होंने शास्त्रीय वैदिक दशा–गोचर के सिद्धांतों को सॉफ्टवेयर में ढाला है। इसलिए जवाब आपकी कुंडली से आता है, न कि किसी के उस दिन के मूड से।",
    "Jaimini system ka spouse-significator — partner ki ek jhalak.": "जैमिनी पद्धति का दारकारक — जीवनसाथी की एक झलक।",
    "Jitna important yeh jaanna hai ki kab yog strong hai, utna hi yeh ki kab नहीं hai. In periods mein rishtey aa sakte hain, par convert hone ka pattern weak rehta hai:": "जितना ज़रूरी यह जानना है कि योग कब मज़बूत है, उतना ही यह भी कि कब नहीं है। इन अवधियों में रिश्ते आ सकते हैं, पर उनके परिणाम तक पहुँचने का पैटर्न कमज़ोर रहता है:",
    "Jo aapne nahi poocha, par jaanna chahenge": "जो आपने नहीं पूछा, पर जानना चाहेंगे",
    "Jo bhi aapko \"pakka shaadi ho jayegi\" bole, woh jhooth bol raha hai. Kundli timing windows batati hai — kab yog strong hai, kab weak. Decision aapka hai; hum sirf timing clear karte hain.": "जो भी आपसे कहे कि \"शादी पक्की हो जाएगी\", वह झूठ बोल रहा है। कुंडली टाइमिंग विंडो बताती है — कब योग मज़बूत है, कब कमज़ोर। फ़ैसला आपका है; हम सिर्फ़ टाइमिंग साफ़ करते हैं।",
    "Jupiter aspects Mars": "गुरु की मंगल पर दृष्टि",
    "Jupiter conjunct Mars": "गुरु की मंगल से युति",
    "Jupiter ka transit is saal neutral zone mein hai — effort par zyada, luck par kam depend kijiye.": "इस साल गुरु का गोचर सामान्य ज़ोन में है — मेहनत पर ज़्यादा, किस्मत पर कम भरोसा कीजिए।",
    "Jupiter ka transit is saal supportive houses mein hai — conversations ko aage badhaane ka saath milega.": "गुरु का गोचर इस साल सहायक भावों में है — बातचीत को आगे बढ़ाने में साथ मिलेगा।",
    "Jupiter ki current condition mein gemstone recommend nahi karte — mantra aur fast kaafi hain.": "गुरु की मौजूदा स्थिति में रत्न की सलाह नहीं देते — मंत्र और व्रत ही काफ़ी हैं।",
    "Jupiter transits 7/1/2/11 from lagna or Moon in window": "विंडो में गुरु का लग्न या चंद्र से 7/1/2/11 भाव में गोचर",
    "Jupiter transits 7/1/2/11 in the window": "इस विंडो में गुरु 7/1/2/11 भावों से गोचर करता है",
    "Jupiter transits over natal 7th lord": "गुरु का गोचर जन्म के 7वें भाव के स्वामी पर",
    "Jupiter transits over your natal 7th lord": "गुरु आपकी जन्म कुंडली के 7वें भाव के स्वामी पर गोचर करता है",
    "Kaise": "कैसे",
    "Kaunsi dasha, kaunsa transit. Blind belief nahi, logic.": "कौन-सी दशा, कौन-सा गोचर। आँख मूँदकर विश्वास नहीं, तर्क।",
    "Keep profiles current and meetings on — matches formed here can absolutely convert, especially in the strongest months. Don't force outcomes; do keep doors open.": "प्रोफ़ाइल अपडेट रखें और मुलाकातें जारी रखें — यहाँ बने रिश्ते ज़रूर आगे बढ़ सकते हैं, खासकर सबसे मज़बूत महीनों में। नतीजों को ज़बरदस्ती न थोपें; पर दरवाज़े खुले रखें।",
    "Kis window mein actively dhoondhna hai, kab prepare karna hai.": "किस विंडो में सक्रिय होकर ढूँढना है, और कब तैयारी करनी है।",
    "Koi astrologer opinion nahi. Sirf calculation.": "कोई ज्योतिषी की राय नहीं। सिर्फ़ गणना।",
    "Koi baat nahi — most people don't. Hum approximate time ke saath kaam karte hain.": "कोई बात नहीं — ज़्यादातर लोगों को नहीं पता होता। हम अनुमानित समय के साथ काम करते हैं।",
    "Kundli timing batati hai; effort aur choice aapke haath mein hai. Strong window mein bhi rishtey dhoondhne padte hain — bas conversion rate better hota hai.": "कुंडली समय बताती है; मेहनत और चुनाव आपके हाथ में है। मज़बूत विंडो में भी रिश्ते ढूँढने पड़ते हैं — बस सफलता की दर बेहतर होती है।",
    "Kya yeh accurate hai?": "क्या यह सटीक है?",
    "Kya yeh computer-generated hai?": "क्या यह कंप्यूटर-जनरेटेड है?",
    "Kyun alag hai": "क्यों अलग है",
    "LAUNCH PRICE": "लॉन्च प्राइस",
    "Lagna": "लग्न",
    "Lagna-based analysis with full house precision.": "लग्न-आधारित विश्लेषण, पूरी भाव सटीकता के साथ।",
    "Lahiri ayanamsa": "Lahiri अयनांश",
    "Lean in.": "आगे बढ़ें।",
    "Listening, learned, connective — knowledge flows through you": "सुनने वाले, विद्वान, जोड़ने वाले — ज्ञान आपके ज़रिए बहता है",
    "Listening, learned, connective — knowledge flows through you.": "सुनने वाले, विद्वान, जोड़ने वाले — ज्ञान आपके ज़रिए बहता है।",
    "Lotus": "कमल",
    "Love for you is passionate and turbulent; the right partner is a steady anchor, not another storm": "आपके लिए प्यार जोशीला और उथल-पुथल भरा है; सही साथी एक स्थिर सहारा होता है, कोई और तूफ़ान नहीं।",
    "Love for you is passionate and turbulent; the right partner is a steady anchor, not another storm.": "आपके लिए प्रेम जुनूनी और उथल-पुथल भरा है; सही साथी एक स्थिर सहारा होता है, कोई और तूफ़ान नहीं।",
    "Love transforms you completely; you need a partner unafraid of your depths": "प्रेम आपको पूरी तरह बदल देता है; आपको ऐसा साथी चाहिए जो आपकी गहराइयों से न घबराए",
    "Love transforms you completely; you need a partner unafraid of your depths.": "प्रेम आपको पूरी तरह बदल देता है; आपको ऐसा साथी चाहिए जो आपकी गहराइयों से न घबराए।",
    "Loved by singles & families": "सिंगल्स और परिवारों की पसंद",
    "Low-activation phase: matches may come but tend not to convert. Delays here are pattern, not personal failure.": "कम सक्रियता का दौर: रिश्ते आ सकते हैं पर अक्सर आगे नहीं बढ़ते। यहाँ देरी एक पैटर्न है, आपकी कोई व्यक्तिगत नाकामी नहीं।",
    "MD lord has a 7th-house connection": "MD का स्वामी 7वें भाव से जुड़ा है",
    "Mahadasha lord is the 7th lord": "महादशा का स्वामी ही 7वें भाव का स्वामी है",
    "Mangal, Ketu — yeh partnership ke rang ko sabse seedha shape dete hain:": "मंगल, केतु — ये साथ के रंग को सबसे सीधे आकार देते हैं:",
    "Mangal, Shukra — yeh partnership ke rang ko sabse seedha shape dete hain:": "मंगल, शुक्र — ये आपके रिश्ते के रंग को सबसे सीधे आकार देते हैं:",
    "Mangalvar (Tuesday)": "मंगलवार",
    "Manglik": "मांगलिक",
    "Manglik analysis": "मांगलिक विश्लेषण",
    "Manglik check": "मांगलिक जाँच",
    "Manglik placement hai — calmly samjhiye": "मांगलिक स्थिति है — इसे शांति से समझिए",
    "Manglik placement hai — par cancelled hai ✅": "मांगलिक स्थिति है — पर वह रद्द हो चुकी है ✅",
    "Manglik status": "मांगलिक स्थिति",
    "Manglik:": "मांगलिक:",
    "Manglik: Haan — page 5 par detail aur cancellation check dekhiye.": "मांगलिक: हाँ — पेज 5 पर ब्यौरा और कैंसलेशन जाँच देखिए।",
    "Manglik: Nahi — is taraf koi rukaawat nahi.": "मांगलिक: नहीं — इस तरफ़ कोई रुकावट नहीं।",
    "Manglik: technically haan, par cancel ho gaya — practically Nahi.": "मांगलिक: तकनीकी रूप से हाँ, पर रद्द हो गया — व्यावहारिक रूप से नहीं।",
    "Mantra:": "मंत्र:",
    "Marriage Timing Report": "मैरिज टाइमिंग रिपोर्ट",
    "Marriage karaka": "मैरिज कारक",
    "Mars aapke chart mein manglik houses (1, 2, 4, 7, 8, 12) mein nahi hai — lagna se bhi, Moon se bhi. Rishtey ki baat-cheet mein yeh sawaal aaye toh confidently 'nahi' kah sakte hain.": "आपकी कुंडली में मंगल मांगलिक भावों (1, 2, 4, 7, 8, 12) में नहीं है — लग्न से भी और चंद्र से भी। रिश्ते की बातचीत में यह सवाल आए तो आप पूरे भरोसे से 'नहीं' कह सकते हैं।",
    "Mars in own or exalted sign": "मंगल अपनी या उच्च राशि में",
    "Mars in own or exalted sign, Jupiter aspects Mars": "मंगल अपनी राशि में या उच्च का, गुरु की मंगल पर दृष्टि",
    "Mars ki current condition mein gemstone recommend nahi karte — mantra aur fast kaafi hain.": "मंगल की मौजूदा स्थिति में रत्न की सलाह नहीं देते — मंत्र और व्रत काफ़ी हैं।",
    "Mars manglik houses mein hai. Yeh koi shraap nahi hai — classical texts iske liye simple remedial framing dete hain, aur manglik-manglik matching mein yeh neutral ho jaata hai. Dar ki nahi, jaankari ki baat hai.": "मंगल मांगलिक भावों में है। यह कोई श्राप नहीं है — शास्त्र इसके लिए एक सरल उपाय बताते हैं, और मांगलिक-मांगलिक मिलान में यह सामान्य हो जाता है। यह डर की नहीं, जानकारी की बात है।",
    "Mars manglik position mein hai, lekin classical cancellation rules apply hote hain:": "मंगल मांगलिक स्थिति में है, लेकिन इस पर शास्त्रीय निवारण के नियम लागू होते हैं:",
    "Meeting context:": "मुलाक़ात का संदर्भ:",
    "Mercury ki current condition mein gemstone recommend nahi karte — mantra aur fast kaafi hain.": "बुध की मौजूदा स्थिति में हम रत्न की सलाह नहीं देते — मंत्र और व्रत ही काफ़ी हैं।",
    "Meri details safe hain?": "मेरी जानकारी सुरक्षित है?",
    "Meri kundli check karo — FREE": "मेरी कुंडली देखिए — FREE",
    "Method": "तरीक़ा",
    "Moderate ≥ 5": "मध्यम ≥ 5",
    "Month": "महीना",
    "Moon ki current condition mein gemstone recommend nahi karte — mantra aur fast kaafi hain.": "चंद्र की मौजूदा स्थिति में हम रत्न की सलाह नहीं देते — मंत्र और व्रत काफ़ी हैं।",
    "Moon sign (Rashi)": "चंद्र राशि (Rashi)",
    "Mujhe birth time nahi pata. Report ban sakti hai?": "मुझे अपना जन्म-समय नहीं पता। क्या फिर भी रिपोर्ट बन सकती है?",
    "Mystic, solitary, healing — you restore what the world breaks": "रहस्यमय, एकांतप्रिय, उपचारक — जिसे दुनिया तोड़ती है, उसे आप फिर से जोड़ते हैं",
    "Mystic, solitary, healing — you restore what the world breaks.": "रहस्यमय, एकांतप्रिय, चंगा करने वाले — दुनिया जो तोड़ती है, उसे आप फिर से सँवारते हैं।",
    "NAHI": "नहीं",
    "NASA JPL data (Swiss Ephemeris)": "NASA JPL डेटा (Swiss Ephemeris)",
    "NASA-grade": "NASA-स्तरीय",
    "Naam": "नाम",
    "Nakshatra": "नक्षत्र",
    "Navamsa": "नवांश",
    "Navamsa (D9) — shaadi ka asli sheesha": "नवांश (D9) — शादी का असली आईना",
    "Navamsa marriage promise ko steadily support karta hai — koi badi rukaawat nahi, D1 windows hi driver hain.": "नवांश मैरिज प्रॉमिस को स्थिर रूप से सहारा देता है — कोई बड़ी रुकावट नहीं, D1 विंडो ही असली चालक हैं।",
    "Navamsa marriage promise ko strongly support karta hai — yog pakka hai, sirf timing ki baat hai (upar windows dekhiye).": "नवांश शादी के वादे का पुरज़ोर समर्थन करता है — योग पक्का है, बस टाइमिंग की बात है (ऊपर विंडो देखिए)।",
    "Navamsa marriage-promise: STEADY": "नवांश का विवाह-वचन: स्थिर",
    "Navamsa marriage-promise: STRONG": "नवांश विवाह-वादा: मज़बूत",
    "Navamsa marriage-promise: TENDER": "नवांश का शादी-वचन: कोमल",
    "Navamsa thoda tender hai — iska matlab shaadi nahi hoti aisa nahi, balki partner-choice aur timing mein soch-samajh zyada zaroori hai. Yeh warning nahi, awareness hai.": "नवांश थोड़ा नाज़ुक है — इसका मतलब यह नहीं कि शादी नहीं होती, बल्कि पार्टनर चुनने और टाइमिंग में थोड़ी ज़्यादा सोच-समझ ज़रूरी है। यह चेतावनी नहीं, बस जागरूकता है।",
    "Netbanking | Instant on-screen delivery": "नेटबैंकिंग | तुरंत स्क्रीन पर डिलीवरी",
    "No": "नहीं",
    "No dasha connection to the 7th house in this period": "इस दौर में 7वें भाव से कोई दशा संबंध नहीं है",
    "Node on 7th axis and AD lord is that node": "7वें अक्ष पर नोड (राहु/केतु) और AD का स्वामी वही नोड है",
    "Nourishing, dutiful, spiritually inclined — people feel safe around you": "पोषण देने वाले, कर्तव्यनिष्ठ, आध्यात्मिक झुकाव वाले — लोग आपके पास ख़ुद को सुरक्षित महसूस करते हैं",
    "Nourishing, dutiful, spiritually inclined — people feel safe around you.": "पोषण देने वाले, कर्तव्यनिष्ठ, आध्यात्मिक झुकाव वाले — लोग आपके साथ सुरक्षित महसूस करते हैं।",
    "Nurturing, complete, transcendent — endings and beginnings meet in you": "पोषण देने वाले, पूर्ण, परे — अंत और शुरुआत आप में मिलते हैं",
    "Nurturing, complete, transcendent — endings and beginnings meet in you.": "पोषण देने वाले, पूर्ण, परे — अंत और शुरुआत आप में मिलते हैं।",
    "Om Ang Angarakaya Namah": "ॐ अं अंगारकाय नमः",
    "Om Ang Angarakaya Namah — 108 baar, Mangalvar (Tuesday) ko": "ॐ अं अंगारकाय नमः — 108 बार, मंगलवार को",
    "Om Brim Brihaspataye Namah": "ॐ ब्रीं बृहस्पतये नमः",
    "Om Brim Brihaspataye Namah — 108 baar, Guruvar (Thursday) ko": "ॐ ब्रीं बृहस्पतये नमः — 108 बार, गुरुवार को",
    "Om Bum Budhaya Namah": "ॐ बुं बुधाय नमः",
    "Om Bum Budhaya Namah — 108 baar, Budhvar (Wednesday) ko": "ॐ बुं बुधाय नमः — 108 बार, बुधवार को",
    "Om Ghrini Suryaya Namah": "ॐ घृणि सूर्याय नमः",
    "Om Ghrini Suryaya Namah — 108 baar, Ravivar (Sunday) ko": "ॐ घृणि सूर्याय नमः — 108 बार, रविवार को",
    "Om Sham Shanaishcharaya Namah": "ॐ शं शनैश्चराय नमः",
    "Om Sham Shanaishcharaya Namah — 108 baar, Shanivar (Saturday) ko": "ॐ शं शनैश्चराय नमः — 108 बार, शनिवार को",
    "Om Shum Shukraya Namah": "ॐ शुं शुक्राय नमः",
    "Om Shum Shukraya Namah — 108 baar, Shukravar (Friday) ko": "ॐ शुं शुक्राय नमः — 108 बार, शुक्रवार को",
    "Om Som Somaya Namah": "ॐ सोम सोमाय नमः",
    "Om Som Somaya Namah — 108 baar, Somvar (Monday) ko": "ॐ सोम सोमाय नमः — 108 बार, सोमवार को",
    "Order yaad rakhiye: pehla remedy hamesha action hai — strong window mein actively dhoondhna. Yeh support hai, substitute nahi.": "क्रम याद रखिए: पहला उपाय हमेशा कर्म ही है — मज़बूत विंडो में सक्रिय होकर ढूँढना। यह सहारा है, विकल्प नहीं।",
    "Partner": "साथी",
    "Partner direction:": "पार्टनर की दिशा:",
    "Partner indications": "साथी के संकेत",
    "Partner ka yog aapke apne circle aur community ke aas-paas ka hai — door ka yog chart mein prominent nahi.": "जीवनसाथी का योग आपके अपने दायरे और समुदाय के आस-पास का है — दूर का योग कुंडली में प्रमुख नहीं है।",
    "Payment ke turant baad, screen par. PDF download aur WhatsApp copy bhi milti hai.": "पेमेंट के तुरंत बाद, स्क्रीन पर। PDF डाउनलोड और WhatsApp कॉपी भी मिलती है।",
    "Pearl (Moti) — only if Moon is well-placed": "मोती (Moti) — सिर्फ़ तभी जब चंद्र अच्छी स्थिति में हो",
    "Pearl (Moti) — only if Moon is well-placed — kisi qualified jeweller/astrologer se trial ke baad hi.": "मोती — सिर्फ़ तभी जब चंद्र अच्छी स्थिति में हो — किसी योग्य जौहरी/ज्योतिषी से ट्रायल के बाद ही।",
    "Pearl / jewel": "मोती / रत्न",
    "Perceptive, private, penetrating — you see what others hide": "गहरी समझ वाले, निजी, पैनी नज़र वाले — जो दूसरे छिपाते हैं, वह आप देख लेते हैं",
    "Perceptive, private, penetrating — you see what others hide.": "गहरी पकड़ वाले, अंतर्मुखी, पैनी नज़र वाले — जो दूसरे छिपाते हैं, वह आप देख लेते हैं।",
    "Period till": "अवधि तक",
    "Pichhle saal": "पिछले साल",
    "Place of birth": "जन्म स्थान",
    "Planetary positions 100% accurate hain — NASA-grade ephemeris data. Timing windows probability hain, appointment nahi. Hum honestly batate hain kaunsa window strong hai aur kaunsa weak — jo koi bhi \"guarantee\" de, usse door rahiye.": "ग्रहों की स्थिति 100% सटीक है — NASA-grade ephemeris डेटा। टाइमिंग विंडो संभावनाएँ हैं, कोई तय अपॉइंटमेंट नहीं। हम ईमानदारी से बताते हैं कि कौन-सी विंडो मज़बूत है और कौन-सी कमज़ोर — जो कोई भी \"गारंटी\" दे, उससे दूर रहिए।",
    "Playful, generous, pleasure-loving — you bring warmth to every room": "खिलंदड़े, उदार, ज़िंदगी का लुत्फ़ उठाने वाले — आप हर महफ़िल में गर्मजोशी लाते हैं",
    "Playful, generous, pleasure-loving — you bring warmth to every room.": "खिलंदड़, उदार, सुख-प्रिय — आप हर महफ़िल में गर्मजोशी लाते हैं।",
    "Prepare.": "तैयारी कीजिए।",
    "Privacy": "प्राइवेसी",
    "Quiet periods": "शांत दौर",
    "Quiet periods — aur unka matlab": "शांत दौर — और उनका मतलब",
    "Raat (10 PM – 4 AM)": "रात (10 PM – 4 AM)",
    "Rahu/12th ka 7th se connection hai — partner doori se, alag community se, ya unexpected background se aane ka yog hai. Surprise ke liye taiyaar rahiye.": "राहु/12वें भाव का 7वें भाव से संबंध है — पार्टनर के किसी दूर से, अलग समुदाय से, या किसी अनपेक्षित पृष्ठभूमि से आने का योग है। किसी सरप्राइज़ के लिए तैयार रहिए।",
    "Rahul Sharma": "Rahul Sharma",
    "Rahul Sharma — Marriage Timing Report | Axtroshastra": "Rahul Sharma — मैरिज टाइमिंग रिपोर्ट | Axtroshastra",
    "Rashi": "राशि",
    "Rashi chart (D1)": "राशि कुंडली (D1)",
    "Ravivar (Sunday)": "रविवार",
    "Razor / flame": "उस्तरा / ज्वाला",
    "Rectification analysis aapke life events se exact time narrow karta hai — windows 6 months tak refine ho sakte hain.": "रेक्टिफिकेशन विश्लेषण आपके जीवन की घटनाओं से सही समय को और सटीक करता है — विंडो 6 महीने तक तक और साफ़ हो सकती हैं।",
    "Red Coral (Moonga) — only if Mars is well-placed": "लाल मूंगा (Moonga) — सिर्फ़ तभी जब मंगल अच्छी स्थिति में हो",
    "Red Coral (Moonga) — only if Mars is well-placed — kisi qualified jeweller/astrologer se trial ke baad hi.": "मूंगा (Red Coral) — तभी जब मंगल अच्छी स्थिति में हो — किसी योग्य जौहरी/ज्योतिषी से ट्रायल के बाद ही।",
    "Refund Policy": "रिफ़ंड नीति",
    "Regal, ancestral, proud — lineage and legacy matter to you": "शाही, कुलीन, स्वाभिमानी — वंश और विरासत आपके लिए मायने रखते हैं।",
    "Regal, ancestral, proud — lineage and legacy matter to you.": "शाही, पुरखों की विरासत वाले, गर्वीले — वंश और विरासत आपके लिए मायने रखते हैं।",
    "Renewing, optimistic, generous — you always find the way back": "नई शुरुआत करने वाले, आशावादी, उदार — आप हमेशा वापसी का रास्ता ढूँढ लेते हैं",
    "Renewing, optimistic, generous — you always find the way back.": "नई शुरुआत करने वाले, आशावादी, उदार — आप हमेशा वापसी का रास्ता ढूँढ लेते हैं।",
    "Report in": "रिपोर्ट में",
    "Report kab milegi?": "रिपोर्ट कब मिलेगी?",
    "Report ke andar": "रिपोर्ट के अंदर",
    "Report mein kya milega": "रिपोर्ट में क्या मिलेगा",
    "Reports are probability estimates from classical Jyotish principles, not guarantees.": "रिपोर्ट शास्त्रीय ज्योतिष सिद्धांतों पर आधारित संभावना के अनुमान हैं, कोई गारंटी नहीं।",
    "Rhythmic, wealthy-spirited, generous — you keep many worlds in beat": "लयबद्ध, समृद्ध मन वाले, उदार — आप कई दुनियाओं को एक ताल में बनाए रखते हैं",
    "Rhythmic, wealthy-spirited, generous — you keep many worlds in beat.": "लयबद्ध, दिल से धनी, उदार — आप कई दुनियाओं को एक ताल में बाँधे रखते हैं।",
    "Rishtey dhoondhne se pehle,": "रिश्ते ढूँढने से पहले,",
    "Rishton ka natural indicator (Venus/Jupiter) — yeh shaadi ka promise dikhata hai.": "रिश्तों का स्वाभाविक संकेतक (शुक्र/गुरु) — यह शादी का वादा दिखाता है।",
    "Romance, celebration and affection are essentials for you, not luxuries": "रोमांस, जश्न और स्नेह आपके लिए ज़रूरतें हैं, विलासिता नहीं",
    "Romance, celebration and affection are essentials for you, not luxuries.": "रोमांस, जश्न और स्नेह आपके लिए ज़रूरतें हैं, कोई विलासिता नहीं।",
    "Ruby (Manik) — only if Sun is well-placed": "माणिक (Ruby) — सिर्फ़ तभी जब सूर्य अच्छी स्थिति में हो",
    "Ruby (Manik) — only if Sun is well-placed — kisi qualified jeweller/astrologer se trial ke baad hi.": "माणिक (Ruby) — सिर्फ़ तभी जब सूर्य अच्छी स्थिति में हो — किसी योग्य जौहरी/ज्योतिषी से ट्रायल के बाद ही।",
    "Saal-dar-saal": "साल-दर-साल",
    "Sabse strong window:": "सबसे मज़बूत विंडो:",
    "Sade Sati check: abhi nahi chal rahi.": "साढ़ेसाती जाँच: अभी नहीं चल रही।",
    "Sade Sati check: chal rahi hai": "साढ़ेसाती जाँच: अभी चल रही है",
    "Saturn ka influence aapke 7th house par hai — timing mein maturity-factor hai. Matlab: shaadi thodi der se, par zyada soch-samajh ke. Late ≠ never.": "शनि का असर आपके 7वें भाव पर है — टाइमिंग में परिपक्वता का पहलू है। मतलब: शादी थोड़ी देर से, पर ज़्यादा सोच-समझकर। देर से ≠ कभी नहीं।",
    "Saturn ka koi direct influence aapke 7th house par nahi — classical 'late marriage' indicator aapke chart mein absent hai.": "शनि का आपके 7वें भाव पर कोई सीधा असर नहीं है — 'देर से शादी' का पारंपरिक संकेत आपकी कुंडली में मौजूद नहीं है।",
    "Saturn ki current condition mein gemstone recommend nahi karte — mantra aur fast kaafi hain.": "शनि की मौजूदा स्थिति में हम रत्न की सलाह नहीं देते — मंत्र और व्रत ही काफ़ी हैं।",
    "Saturn sits on the 7th axis for most of the window": "विंडो के ज़्यादातर समय शनि 7वें भाव की धुरी पर बैठा रहता है",
    "Sawaal-jawaab": "सवाल-जवाब",
    "Searching, gentle, restless — always seeking the next meaningful thing": "खोजी, कोमल, बेचैन — हमेशा अगली सार्थक चीज़ की तलाश में",
    "Searching, gentle, restless — always seeking the next meaningful thing.": "तलाश में रहने वाले, कोमल, बेचैन — हमेशा अगली सार्थक चीज़ की खोज में।",
    "Senior, intense, protective — you carry responsibility early": "बड़े, गहन, संरक्षक — आप ज़िम्मेदारी जल्दी उठा लेते हैं",
    "Senior, intense, protective — you carry responsibility early.": "गंभीर, प्रगाढ़, रक्षात्मक — आप ज़िम्मेदारी कम उम्र में ही उठा लेते हैं।",
    "Shaadi": "शादी",
    "Shaadi Kab Hogi? — Marriage Timing Report | Axtroshastra": "शादी कब होगी? — मैरिज टाइमिंग रिपोर्ट | Axtroshastra",
    "Shaadi ka main switch. Iski dignity (upar) timing ki quality batati hai — strong matlab saaf timing, tender matlab zyada soch-samajh.": "शादी का मुख्य स्विच। इसकी दशा-स्थिति (ऊपर) टाइमिंग की गुणवत्ता बताती है — मज़बूत यानी साफ़ टाइमिंग, नरम यानी ज़्यादा सोच-समझ की ज़रूरत।",
    "Shaadi kab hogi? — seedha jawab": "शादी कब होगी? — सीधा जवाब",
    "Shaadi, partner aur commitment ka ghar — marriage ka main area.": "शादी, साथी और प्रतिबद्धता का भाव — शादी का मुख्य क्षेत्र।",
    "Shaam (4 PM – 10 PM)": "शाम (4 PM – 10 PM)",
    "Shani, Ketu — yeh partnership ke rang ko sabse seedha shape dete hain:": "शनि, केतु — ये आपके रिश्ते के रंग को सबसे सीधे तरीके से आकार देते हैं:",
    "Shani, Rahu — yeh partnership ke rang ko sabse seedha shape dete hain:": "शनि, राहु — ये पार्टनरशिप के रंग को सबसे सीधे तौर पर आकार देते हैं:",
    "Shanivar (Saturday)": "शनिवार",
    "Share on WhatsApp": "WhatsApp पर शेयर करें",
    "Sharp, purifying, protective — you cut through confusion for yourself and others": "तेज़, शुद्ध करने वाले, रक्षक — आप अपने और दूसरों के लिए उलझन को चीरकर रास्ता साफ़ करते हैं।",
    "Sharp, purifying, protective — you cut through confusion for yourself and others.": "तेज़, निखारने वाले, रक्षक — आप अपने और दूसरों के लिए उलझनों को काटकर रास्ता साफ करते हैं।",
    "Shukra, Ketu — yeh partnership ke rang ko sabse seedha shape dete hain:": "शुक्र, केतु — ये साथ के रंग को सबसे सीधे आकार देते हैं:",
    "Shukra, Rahu — yeh partnership ke rang ko sabse seedha shape dete hain:": "शुक्र, राहु — ये आपके रिश्ते के रंग को सबसे सीधे आकार देते हैं:",
    "Shukravar (Friday)": "शुक्रवार",
    "Sirf sheher ya zila kaafi hai — locality (jaise Punjabi Bagh) search mein nahi aayegi.": "सिर्फ़ शहर या ज़िला ही काफ़ी है — कोई मोहल्ला (जैसे Punjabi Bagh) सर्च में नहीं आएगा।",
    "Skilled, witty, resourceful — you fix things, literally and socially": "हुनरमंद, हाज़िरजवाब, जुगाड़ू — आप चीज़ें सँभालते हैं, सचमुच भी और रिश्तों में भी",
    "Skilled, witty, resourceful — you fix things, literally and socially.": "कुशल, हाज़िरजवाब, संसाधनपूर्ण — आप चीज़ें ठीक करते हैं, सचमुच और रिश्तों में भी।",
    "Somvar (Monday)": "सोमवार",
    "Status + cancellation rules. (Spoiler: \"manglik\" sunke darne ki zaroorat aksar nahi hoti.)": "स्टेटस + कैंसलेशन नियम। (एक बात: \"मांगलिक\" सुनकर डरने की ज़रूरत अक्सर नहीं होती।)",
    "Stay active.": "सक्रिय रहिए।",
    "Steady, magnetic, growth-giving — things flourish under your care": "स्थिर, आकर्षक, विकास देने वाले — आपकी देखभाल में चीज़ें फलती-फूलती हैं",
    "Steady, magnetic, growth-giving — things flourish under your care.": "स्थिर, आकर्षक, आगे बढ़ाने वाले — आपकी देखभाल में चीज़ें फलती-फूलती हैं।",
    "Sthiti": "स्थिति",
    "Stormy, brilliant, transformative — you grow through intensity": "तूफ़ानी, शानदार, बदलाव लाने वाले — आप तीव्रता से गुज़रकर आगे बढ़ते हैं",
    "Stormy, brilliant, transformative — you grow through intensity.": "तूफ़ानी, तेजस्वी, बदलाव लाने वाले — आप तीव्रता से गुज़रकर बढ़ते हैं।",
    "Subah (4 AM – 10 AM)": "सुबह (4 AM – 10 AM)",
    "Summary": "सारांश",
    "Sun ki current condition mein gemstone recommend nahi karte — mantra aur fast kaafi hain.": "सूर्य की मौजूदा स्थिति में हम रत्न की सलाह नहीं देते — मंत्र और व्रत ही काफ़ी हैं।",
    "Surya, Budh — yeh partnership ke rang ko sabse seedha shape dete hain:": "सूर्य, बुध — ये साथ के रंग को सबसे सीधे आकार देते हैं:",
    "Surya, Budh, Guru — yeh partnership ke rang ko sabse seedha shape dete hain:": "सूर्य, बुध, गुरु — ये आपके रिश्ते के रंग को सबसे सीधे आकार देते हैं:",
    "Surya, Budh, Shukra — yeh partnership ke rang ko sabse seedha shape dete hain:": "सूर्य, बुध, शुक्र — ये साझेदारी के रंग को सबसे सीधे आकार देते हैं:",
    "Surya, Chandra — yeh partnership ke rang ko sabse seedha shape dete hain:": "सूर्य, चंद्र — ये आपके रिश्ते के रंग को सबसे सीधे तरीके से आकार देते हैं:",
    "Surya, Guru — yeh partnership ke rang ko sabse seedha shape dete hain:": "सूर्य, गुरु — ये साझेदारी के रंग को सबसे सीधे आकार देते हैं:",
    "Surya, Ketu — yeh partnership ke rang ko sabse seedha shape dete hain:": "सूर्य, केतु — ये साथ के रंग को सबसे सीधे आकार देते हैं:",
    "Surya, Shukra — yeh partnership ke rang ko sabse seedha shape dete hain:": "सूर्य, शुक्र — ये आपके रिश्ते के रंग को सबसे सीधे तरीके से आकार देते हैं:",
    "Sword / two-faced man": "तलवार / दो-मुँहा व्यक्ति",
    "Teardrop / gem": "आँसू की बूँद / रत्न",
    "Technical: Mars from lagna — clear; from Moon — clear.": "तकनीकी: मंगल लग्न से — साफ़; चंद्र से — साफ़।",
    "Technical: Mars from lagna — clear; from Moon — manglik houses mein.": "तकनीकी: मंगल लग्न से — साफ़; चंद्र से — मांगलिक भावों में।",
    "Technical: Mars from lagna — manglik houses mein; from Moon — clear.": "तकनीकी: लग्न से मंगल — मांगलिक भावों में; चंद्र से — साफ़।",
    "Technical: Mars from lagna — manglik houses mein; from Moon — manglik houses mein.": "तकनीकी: मंगल लग्न से — मांगलिक भावों में; चंद्र से — मांगलिक भावों में।",
    "Terms": "शर्तें",
    "The Answer": "जवाब",
    "Throne": "सिंहासन",
    "Time of birth": "जन्म का समय",
    "Timeline 2026–2036, har window ka strength grade — Strong / Moderate / Building.": "टाइमलाइन 2026–2036, हर विंडो का स्ट्रेंथ ग्रेड — मज़बूत / मध्यम / निर्माणाधीन।",
    "Timing windows probability bands hain, appointments nahi — ±15 minute ka birth time difference bhi boundaries ko months tak shift kar sakta hai. Isliye hum honest ranges dete hain, fake precision nahi.": "टाइमिंग विंडो संभावना की रेंज होती हैं, तयशुदा तारीखें नहीं — जन्म समय में सिर्फ़ ±15 मिनट का फ़र्क भी सीमाओं को महीनों तक खिसका सकता है। इसीलिए हम ईमानदार रेंज देते हैं, नकली सटीकता नहीं।",
    "Top window:": "सबसे बेहतर विंडो:",
    "Total": "कुल",
    "Traditional astrologers apne experience se batate hain — har astrologer alag jawab deta hai. Hum aapki kundli ko NASA-grade planetary data se compute karte hain — wahi calculations jo professional observatories use karti hain (NASA JPL ephemeris). Same chart, same answer, every time.": "पारंपरिक ज्योतिषी अपने अनुभव से बताते हैं — हर ज्योतिषी अलग जवाब देता है। हम आपकी कुंडली को NASA-grade ग्रहीय डेटा से गणना करते हैं — वही गणनाएँ जो professional observatories इस्तेमाल करती हैं (NASA JPL ephemeris)। वही कुंडली, वही जवाब, हर बार।",
    "Traditional support — bina dar ke": "पारंपरिक सहारा — बिना डर के",
    "Treat serious conversations in this period seriously — involve family early, say yes to meetings, and don't postpone decisions that feel right. This is your highest-activation phase.": "इस दौर में गंभीर बातचीत को गंभीरता से लें — परिवार को जल्दी शामिल करें, मुलाकातों के लिए हाँ कहें, और जो फ़ैसले सही लगें उन्हें टालें नहीं। यह आपका सबसे सक्रिय दौर है।",
    "Triumphal archway": "विजय-तोरण",
    "Twins / serpent of the deep": "जुड़वाँ / गहराई का सर्प",
    "UPI": "UPI",
    "Under the hood": "पर्दे के पीछे",
    "Universal, principled, enduring — you win slowly and permanently": "सार्वभौमिक, सिद्धांतवादी, टिकाऊ — आप धीरे-धीरे पर हमेशा के लिए जीतते हैं",
    "Universal, principled, enduring — you win slowly and permanently.": "सार्वभौमिक, सिद्धांतवादी, टिकाऊ — आप धीरे-धीरे पर हमेशा के लिए जीतते हैं।",
    "Unlock my report —": "मेरी रिपोर्ट अनलॉक करें —",
    "Use this phase to get ready — clarity on what you want, conversations with family, self-work. Momentum built here pays off in the next stronger window.": "इस दौर का इस्तेमाल तैयारी के लिए कीजिए — आप क्या चाहते हैं इस पर साफ़ सोच, परिवार से बातचीत, और खुद पर काम। यहाँ बनी रफ़्तार अगली मज़बूत विंडो में रंग लाती है।",
    "Vargottama (D1 aur D9 mein ek hi rashi — extra strong):": "वर्गोत्तम (D1 और D9 में एक ही राशि — और भी मज़बूत):",
    "Venus (marriage karaka) vargottama hai — sneh aur nibhaav ki strength": "शुक्र (मैरिज कारक) वर्गोत्तम है — स्नेह और निभाव की मज़बूती",
    "Venus D9 mein debilitated hai — expression mein narmi ki zaroorat": "शुक्र D9 में नीच है — भाव ज़ाहिर करने में नरमी की ज़रूरत",
    "Venus in D9": "D9 में शुक्र",
    "Venus ki current condition mein gemstone recommend nahi karte — mantra aur fast kaafi hain.": "शुक्र की मौजूदा स्थिति में रत्न की सलाह नहीं देते — मंत्र और व्रत ही काफी हैं।",
    "Vrat/fast:": "व्रत/उपवास:",
    "Weak periods": "कमज़ोर दौर",
    "Weak periods explained": "कमज़ोर दौर की व्याख्या",
    "Weak periods mein": "कमज़ोर दौर में",
    "WhatsApp +91 95998 27297": "WhatsApp +91 95998 27297",
    "WhatsApp Support": "WhatsApp सहायता",
    "WhatsApp par CAREER bhejiye →": "WhatsApp पर CAREER भेजिए →",
    "WhatsApp: +91 95998 27297": "WhatsApp: +91 95998 27297",
    "Whole-sign houses": "होल-साइन भाव",
    "Windows are probability estimates from classical dasha–transit principles, not guarantees.": "विंडो शास्त्रीय दशा–गोचर सिद्धांतों पर आधारित संभावना के अनुमान हैं, कोई गारंटी नहीं।",
    "Windows calculate ho rahe hain…": "आपकी विंडो गिनी जा रही हैं…",
    "Windows calculated. Exact years, months aur strength grade report mein.": "विंडो निकल गईं। सटीक साल, महीने और मज़बूती ग्रेड रिपोर्ट में।",
    "Wise, compassionate, stabilising — the calm after others' storms": "समझदार, दयालु, स्थिर करने वाले — दूसरों के तूफ़ानों के बाद की शांति",
    "Wise, compassionate, stabilising — the calm after others' storms.": "समझदार, दयालु, स्थिर करने वाले — दूसरों के तूफ़ानों के बाद की शांति।",
    "Yahi hamari specialty hai.": "यही हमारी ख़ासियत है।",
    "Yeh 6-7 factors milkar aapki marriage timing decide karte hain. Agle page par inhi se nikale gaye aapke windows hain.": "ये 6-7 बातें मिलकर आपकी शादी की टाइमिंग तय करती हैं। अगले पेज पर इन्हीं से निकाली गई आपकी विंडो हैं।",
    "Yeh indications hain, portrait nahi — chart directions batata hai, details zindagi bharti hai.": "ये संकेत हैं, पूरी तस्वीर नहीं — कुंडली दिशा बताती है, ब्योरे ज़िंदगी भरती है।",
    "Yeh jawab aapke poore chart se nikla hai. Neeche har window ki wajah, aapka Navamsa, aur beete periods — taaki aap khud milaa sakein.": "यह जवाब आपकी पूरी कुंडली से निकला है। नीचे हर विंडो की वजह, आपका नवांश, और बीते हुए दौर — ताकि आप खुद मिला सकें।",
    "Yeh kaun log hain?": "ये कौन लोग हैं?",
    "Yeh page save kar lijiye — har saal ke shuru mein dobara padhne layak hai.": "यह पेज सेव कर लीजिए — हर साल की शुरुआत में दोबारा पढ़ने लायक है।",
    "Yeh report Axtroshastra ne banayi — apna report paayein:": "यह रिपोर्ट Axtroshastra ने बनाई — अपनी रिपोर्ट पाएँ:",
    "Yeh report alag kyun hai": "यह रिपोर्ट अलग क्यों है",
    "Yeh report classical Vedic Jyotish (dasha-transit) principles par computed hai — guidance ke liye, guarantee nahi. Timing windows probability hain, fixed dates nahi. Yeh legal, medical ya financial advice nahi hai. Apne life decisions aap apni samajh se lijiye; Axtroshastra kisi outcome ki zimmedari nahi leta.": "यह रिपोर्ट शास्त्रीय वैदिक ज्योतिष (दशा-गोचर) सिद्धांतों पर आधारित है — मार्गदर्शन के लिए, गारंटी नहीं। टाइमिंग विंडो संभावनाएँ हैं, तय तारीखें नहीं। यह कानूनी, चिकित्सीय या वित्तीय सलाह नहीं है। अपने जीवन के फैसले आप अपनी समझ से लीजिए; Axtroshastra किसी परिणाम की ज़िम्मेदारी नहीं लेता।",
    "Yeh section isliye hai taaki aap dekh sakein: timing ek pattern hai, aapki kami nahi. Jo beet gaya usmein bhi chart ka logic tha.": "यह हिस्सा इसलिए है ताकि आप देख सकें: समय एक पैटर्न है, आपकी कमी नहीं। जो बीत गया उसमें भी कुंडली का अपना तर्क था।",
    "Yeh windows kaise nikle": "ये विंडो कैसे निकलीं",
    "Yellow Sapphire (Pukhraj) — only if Jupiter is well-placed": "पीला पुखराज (पुखराज) — केवल तभी जब गुरु अच्छी स्थिति में हो",
    "Yellow Sapphire (Pukhraj) — only if Jupiter is well-placed — kisi qualified jeweller/astrologer se trial ke baad hi.": "पुखराज (Yellow Sapphire) — तभी जब गुरु अच्छी स्थिति में हो — किसी योग्य जौहरी/ज्योतिषी से ट्रायल के बाद ही।",
    "Yes — see page 5": "हाँ — पेज 5 देखें",
    "Yoni": "योनि",
    "You are attracted to charm and polish; the lesson is choosing substance beneath the shine": "आप आकर्षण और चमक की ओर खिंचते हैं; सीख यही है कि चमक के नीचे छिपे असली गुण को चुनें",
    "You are attracted to charm and polish; the lesson is choosing substance beneath the shine.": "आप आकर्षण और चमक-दमक की ओर खिंचते हैं; सीख यह है कि चमक के नीचे छिपे असल गुण को चुनें।",
    "You are built for deep committed partnership; loyalty comes naturally and is deeply needed in return": "आप गहरे, प्रतिबद्ध साथ के लिए बने हैं; वफ़ादारी आपमें सहज है और बदले में उतनी ही ज़रूरी भी।",
    "You are built for deep committed partnership; loyalty comes naturally and is deeply needed in return.": "आप गहरे, निभाने वाले रिश्ते के लिए बने हैं; वफ़ादारी आपमें सहज है और बदले में उतनी ही गहराई से चाहिए भी।",
    "You are romantic and devoted; stability and sensory comfort are your love languages": "आप रोमांटिक और समर्पित हैं; स्थिरता और सुख-आराम आपके प्यार जताने के तरीके हैं",
    "You are romantic and devoted; stability and sensory comfort are your love languages.": "आप रोमांटिक और समर्पित हैं; स्थिरता और संवेदी सुकून आपके प्रेम को व्यक्त करने के तरीके हैं।",
    "You are the steady one in love; your challenge is asking for the care you constantly give": "प्यार में आप स्थिर रहने वाले हैं; आपकी चुनौती यह है कि जो देखभाल आप हमेशा देते हैं, उसे माँगना सीखें",
    "You are the steady one in love; your challenge is asking for the care you constantly give.": "प्रेम में आप स्थिर रहने वाले हैं; आपकी चुनौती है वह देखभाल माँगना जो आप हमेशा दूसरों को देते हैं।",
    "You commit for the long arc; you value character over chemistry, and keep both when you find them": "आप लंबे सफ़र के लिए प्रतिबद्ध होते हैं; आप चरित्र को केमिस्ट्री से ऊपर रखते हैं, और जब दोनों मिल जाएँ तो दोनों को सँभालकर रखते हैं",
    "You commit for the long arc; you value character over chemistry, and keep both when you find them.": "आप लंबे सफर के लिए प्रतिबद्ध होते हैं; आप केमिस्ट्री से ज़्यादा चरित्र को महत्व देते हैं, और जब दोनों मिल जाएँ तो दोनों को संभालकर रखते हैं।",
    "You express love through care and service; you flourish with a partner who reciprocates, not just receives": "आप प्यार को देखभाल और सेवा के ज़रिए ज़ाहिर करते हैं; आप ऐसे साथी के साथ खिलते हैं जो सिर्फ़ पाता नहीं, बल्कि उतना ही लौटाता भी है।",
    "You express love through care and service; you flourish with a partner who reciprocates, not just receives.": "आप देखभाल और सेवा के ज़रिए प्यार जताते हैं; आप उस पार्टनर के साथ खिलते हैं जो सिर्फ़ लेता नहीं, बल्कि उतना ही लौटाता भी है।",
    "You fall for minds; conversation is your intimacy, silence together your comfort": "आप दिमाग़ों पर फ़िदा होते हैं; बातचीत आपकी नज़दीकी है, और साथ की ख़ामोशी आपका सुकून",
    "You fall for minds; conversation is your intimacy, silence together your comfort.": "आप सोच-समझ पर मोहित होते हैं; बातचीत ही आपकी नज़दीकी है, और साथ में चुप्पी आपका सुकून।",
    "You forgive easily and love expansively; you need a partner who values your goodness, not exploits it": "आप आसानी से माफ़ कर देते हैं और खुले दिल से प्यार करते हैं; आपको ऐसा साथी चाहिए जो आपकी अच्छाई की कद्र करे, उसका फ़ायदा न उठाए",
    "You forgive easily and love expansively; you need a partner who values your goodness, not exploits it.": "आप आसानी से माफ़ कर देते हैं और खुले दिल से प्यार करते हैं; आपको ऐसा पार्टनर चाहिए जो आपकी अच्छाई की कद्र करे, उसका फ़ायदा न उठाए।",
    "You guard your heart; intimacy comes in layers, and betrayal is the one unforgivable": "आप अपना दिल संभालकर रखते हैं; नज़दीकी परत-दर-परत आती है, और धोखा वो एक बात है जो माफ़ नहीं होती",
    "You guard your heart; intimacy comes in layers, and betrayal is the one unforgivable.": "आप अपने दिल की हिफ़ाज़त करते हैं; आत्मीयता परतों में खुलती है, और विश्वासघात एकमात्र ऐसी बात है जिसे आप कभी माफ़ नहीं कर सकते।",
    "You love deeply and possessively; trust built slowly, but once built, unshakeable": "आप गहराई से और अधिकार-भाव के साथ प्यार करते हैं; भरोसा धीरे-धीरे बनता है, पर एक बार बन जाए तो अटूट",
    "You love deeply and possessively; trust built slowly, but once built, unshakeable.": "आप गहराई से और अपनेपन से प्यार करते हैं; भरोसा धीरे-धीरे बनता है, पर एक बार बन गया तो अटूट।",
    "You love selflessly and dream deeply; you need a partner who protects your softness": "आप निःस्वार्थ प्रेम करते हैं और गहरे सपने देखते हैं; आपको ऐसा साथी चाहिए जो आपकी कोमलता की रक्षा करे",
    "You love selflessly and dream deeply; you need a partner who protects your softness.": "आप निःस्वार्थ भाव से प्यार करते हैं और गहरे सपने देखते हैं; आपको ऐसा साथी चाहिए जो आपकी कोमलता की रक्षा करे।",
    "You love wholeheartedly and expect faith in your comeback; doubt from a partner wounds most": "आप पूरे दिल से प्यार करते हैं और अपने लौटने पर भरोसा चाहते हैं; जीवनसाथी का शक ही सबसे गहरा घाव देता है",
    "You love wholeheartedly and expect faith in your comeback; doubt from a partner wounds most.": "आप पूरे दिल से प्रेम करते हैं और चाहते हैं कि आपकी वापसी पर भरोसा किया जाए; पार्टनर का शक आपको सबसे ज़्यादा चोट पहुँचाता है।",
    "You love with dignity and expect respect; public loyalty from a partner matters as much as private love": "आप गरिमा के साथ प्रेम करते हैं और सम्मान की उम्मीद रखते हैं; साथी की सबके सामने निभाई वफ़ादारी आपके लिए उतनी ही मायने रखती है जितना निजी प्यार",
    "You love with dignity and expect respect; public loyalty from a partner matters as much as private love.": "आप गरिमा के साथ प्रेम करते हैं और सम्मान की उम्मीद रखते हैं; पार्टनर की सबके सामने निभाई गई वफ़ादारी आपके लिए उतनी ही मायने रखती है जितना निजी प्यार।",
    "You love with purpose; partnership works when you are building something together": "आप एक मक़सद के साथ प्रेम करते हैं; रिश्ता तभी चलता है जब आप दोनों मिलकर कुछ बना रहे हों",
    "You love with purpose; partnership works when you are building something together.": "आप एक मक़सद के साथ प्रेम करते हैं; साथ तभी निभता है जब आप दोनों मिलकर कुछ बना रहे हों।",
    "You need a partner in rhythm with your ambitions; you give abundantly when met halfway": "आपको ऐसा साथी चाहिए जो आपकी महत्वाकांक्षाओं के साथ क़दम मिलाकर चले; जब सामने से आधा रास्ता तय हो, तो आप भरपूर देते हैं",
    "You need a partner in rhythm with your ambitions; you give abundantly when met halfway.": "आपको ऐसा साथी चाहिए जो आपकी महत्वाकांक्षाओं के साथ कदम मिलाए; जब कोई आधा रास्ता तय करे, तो आप दिल खोलकर देते हैं।",
    "You need mental chase and novelty in love; boredom, not conflict, is your relationship risk": "आपको प्यार में दिमागी खिंचाव और नयापन चाहिए; आपके रिश्ते का ख़तरा टकराव नहीं, बल्कि ऊब है",
    "You need mental chase and novelty in love; boredom, not conflict, is your relationship risk.": "प्रेम में आपको मानसिक जुड़ाव और नयापन चाहिए; आपके रिश्ते का ख़तरा टकराव नहीं, बल्कि ऊब है।",
    "You need real space and real depth; shallow closeness drains you, true intimacy heals you": "आपको सच्ची जगह और सच्ची गहराई चाहिए; ऊपरी नज़दीकी आपको थका देती है, सच्ची आत्मीयता आपको सँवार देती है",
    "You need real space and real depth; shallow closeness drains you, true intimacy heals you.": "आपको सच्ची जगह और सच्ची गहराई चाहिए; ऊपरी नज़दीकी आपको थका देती है, सच्ची नज़दीकी आपको सुकून देती है।",
    "You need space inside love; the right partner holds you loosely and gains all of you": "प्यार में आपको अपनी जगह चाहिए; सही साथी आपको ढीला थामता है और पूरा आपको पा लेता है",
    "You need space inside love; the right partner holds you loosely and gains all of you.": "प्यार में आपको अपनी जगह चाहिए; सही साथी आपको ढीला थामता है और पूरा आपको पा लेता है।",
    "You protect the ones you love fiercely; softness is there, under the armour": "आप अपने प्यारों की जी-जान से रक्षा करते हैं; कोमलता भी है, बस उस कवच के नीचे",
    "You protect the ones you love fiercely; softness is there, under the armour.": "आप अपने प्रियजनों की जी-जान से रक्षा करते हैं; नरमी भी है, बस उस कवच के नीचे छिपी है।",
    "You show love through practical help and humour; you need appreciation, not grand drama": "आप व्यावहारिक मदद और हँसी-मज़ाक से प्यार जताते हैं; आपको बड़े नाटक नहीं, बस सराहना चाहिए",
    "You show love through practical help and humour; you need appreciation, not grand drama.": "आप व्यावहारिक मदद और हँसी-मज़ाक से प्यार जताते हैं; आपको बड़े नाटक नहीं, बस सराहना चाहिए।",
    "You take commitment seriously and expect the same; casual love does not satisfy you": "आप रिश्ते को गंभीरता से लेते हैं और वैसा ही चाहते हैं; हल्का-फुल्का प्यार आपको संतुष्ट नहीं करता",
    "You take commitment seriously and expect the same; casual love does not satisfy you.": "आप प्रतिबद्धता को गंभीरता से लेते हैं और वैसी ही उम्मीद रखते हैं; हल्का-फुल्का प्यार आपको संतुष्ट नहीं करता।",
    "You test partners early; behind the sharpness is fierce loyalty to the one who passes": "आप साथी को शुरू में ही परखते हैं; उस तीखेपन के पीछे उसके लिए गहरी वफ़ादारी छिपी होती है जो परख में खरा उतरे।",
    "You test partners early; behind the sharpness is fierce loyalty to the one who passes.": "आप साथी को शुरू में ही परखते हैं; उस तीखेपन के पीछे उसके लिए गहरी वफ़ादारी छिपी है जो इस परख में खरा उतरे।",
    "You're in good company": "आप अच्छी संगत में हैं",
    "Young sprout in wind": "हवा में नन्हा अंकुर",
    "Your love-style is adventurous and idealistic — love must have meaning and room to roam — Venus combust hai, isliye expression mein hesitation aa sakti hai; feelings genuine, awaaz dheemi..": "आपका प्यार का अंदाज़ साहसी और आदर्शवादी है — प्यार में मायने भी हों और खुलकर घूमने की जगह भी — शुक्र अस्त है, इसलिए इज़हार में थोड़ी हिचकिचाहट आ सकती है; भावनाएँ सच्ची हैं, बस आवाज़ धीमी है।",
    "Your love-style is adventurous and idealistic — love must have meaning and room to roam.": "आपका प्रेम का अंदाज़ साहसी और आदर्शवादी है — प्रेम में मतलब भी हो और घूमने-फिरने की आज़ादी भी।",
    "Your love-style is careful and devoted — you love through acts of service and quiet standards — Venus combust hai, isliye expression mein hesitation aa sakti hai; feelings genuine, awaaz dheemi..": "आपका प्रेम करने का अंदाज़ सोच-समझकर और समर्पित है — आप सेवा और अपने शांत उसूलों के ज़रिए प्यार जताते हैं — शुक्र अस्त है, इसलिए जताने में थोड़ी झिझक आ सकती है; भावनाएँ सच्ची, बस आवाज़ धीमी..",
    "Your love-style is careful and devoted — you love through acts of service and quiet standards.": "आपका प्यार का अंदाज़ सोच-समझकर और समर्पित है — आप सेवा भाव और शांत उसूलों के ज़रिए प्यार जताते हैं।",
    "Your love-style is direct and impulsive in love — you pursue openly and lose interest in games — Venus combust hai, isliye expression mein hesitation aa sakti hai; feelings genuine, awaaz dheemi..": "प्यार में आपका अंदाज़ सीधा और आवेगी है — आप खुलकर आगे बढ़ते हैं और दिखावे-नाटक में रुचि खो देते हैं — शुक्र अस्त है, इसलिए भावनाएँ ज़ाहिर करने में थोड़ी झिझक आ सकती है; भावनाएँ सच्ची, आवाज़ धीमी..",
    "Your love-style is direct and impulsive in love — you pursue openly and lose interest in games.": "आपका प्रेम-अंदाज़ सीधा और आवेगपूर्ण है — आप खुलकर आगे बढ़ते हैं और दिखावे के खेलों में दिलचस्पी खो देते हैं।",
    "Your love-style is grand and warm-hearted — romance should feel like celebration.": "आपका प्यार का अंदाज़ भव्य और गर्मजोशी भरा है — रोमांस किसी जश्न जैसा महसूस होना चाहिए।",
    "Your love-style is harmonising and partnership-built — you are at your best in a committed pair — Venus apne hi sign mein strong hai; pyaar mein aapki instinct par bharosa kiya ja sakta hai..": "आपका प्रेम का अंदाज़ तालमेल बिठाने वाला और साथ निभाने के लिए बना है — किसी प्रतिबद्ध जोड़ी में आप अपने सबसे अच्छे रूप में होते हैं — शुक्र अपनी ही राशि में मज़बूत है; प्यार में आपकी सहज समझ पर भरोसा किया जा सकता है।।",
    "Your love-style is intense and all-or-nothing — you love deeply or not at all — Venus combust hai, isliye expression mein hesitation aa sakti hai; feelings genuine, awaaz dheemi..": "आपका प्रेम करने का अंदाज़ गहरा और पूरा-या-कुछ नहीं वाला है — आप या तो दिल से प्यार करते हैं या बिल्कुल नहीं — शुक्र अस्त है, इसलिए जताने में थोड़ी झिझक आ सकती है; भावनाएँ सच्ची, बस आवाज़ धीमी..",
    "Your love-style is intense and all-or-nothing — you love deeply or not at all.": "आपका प्रेम-अंदाज़ गहरा और सब-या-कुछ-नहीं वाला है — या तो आप गहराई से प्यार करते हैं या बिल्कुल नहीं।",
    "Your love-style is playful and verbal — flirting is conversation, and conversation is intimacy — Venus combust hai, isliye expression mein hesitation aa sakti hai; feelings genuine, awaaz dheemi..": "आपका प्रेम-अंदाज़ चंचल और बातूनी है — फ़्लर्ट करना बातचीत है, और बातचीत ही नज़दीकी है — शुक्र अस्त है, इसलिए भावनाएँ ज़ाहिर करने में झिझक आ सकती है; भावनाएँ सच्ची, आवाज़ धीमी..",
    "Your love-style is playful and verbal — flirting is conversation, and conversation is intimacy.": "आपका प्रेम-अंदाज़ मज़ाकिया और बातों वाला है — फ्लर्ट करना बातचीत है, और बातचीत ही नज़दीकी है।",
    "Your love-style is protective and emotional — you love like family, deep and enveloping — Venus combust hai, isliye expression mein hesitation aa sakti hai; feelings genuine, awaaz dheemi..": "आपका प्रेम-अंदाज़ रक्षात्मक और भावुक है — आप परिवार की तरह प्यार करते हैं, गहरा और सब कुछ समेट लेने वाला — शुक्र अस्त है, इसलिए भावनाएँ ज़ाहिर करने में हिचकिचाहट आ सकती है; जज़्बात सच्चे, आवाज़ धीमी..",
    "Your love-style is protective and emotional — you love like family, deep and enveloping.": "आपका प्रेम-अंदाज़ रक्षात्मक और भावनात्मक है — आप परिवार की तरह प्यार करते हैं, गहरा और समेट लेने वाला।",
    "Your love-style is reserved and enduring — slow to open, near-impossible to shake once committed — Venus combust hai, isliye expression mein hesitation aa sakti hai; feelings genuine, awaaz dheemi..": "आपकी प्रेम-शैली संयमित और टिकाऊ है — खुलने में समय लेती है, पर एक बार प्रतिबद्ध हो जाएँ तो डिगाना लगभग नामुमकिन — शुक्र अस्त है, इसलिए भावनाएँ ज़ाहिर करने में झिझक आ सकती है; भावनाएँ सच्ची, आवाज़ धीमी..",
    "Your love-style is reserved and enduring — slow to open, near-impossible to shake once committed.": "प्यार में आपका अंदाज़ संयमित और टिकाऊ है — खुलने में समय लगता है, पर एक बार प्रतिबद्ध हो गए तो डिगाना लगभग नामुमकिन।",
    "Your love-style is romantic and self-giving — you love like poetry, and must guard against over-giving — Venus apne hi sign mein strong hai; pyaar mein aapki instinct par bharosa kiya ja sakta hai..": "आपकी प्रेम-शैली रोमांटिक और समर्पित है — आप कविता की तरह प्यार करते हैं, और ज़रूरत से ज़्यादा दे देने से बचना ज़रूरी है — शुक्र अपनी ही राशि में मज़बूत है; प्यार में आपकी अंतरात्मा की आवाज़ पर भरोसा किया जा सकता है..",
    "Your love-style is romantic and self-giving — you love like poetry, and must guard against over-giving — Venus combust hai, isliye expression mein hesitation aa sakti hai; feelings genuine, awaaz dheemi..": "आपका प्रेम-अंदाज़ रोमांटिक और समर्पित है — आप कविता की तरह प्रेम करते हैं, और आपको ज़रूरत से ज़्यादा देने से बचना चाहिए — शुक्र अस्त है, इसलिए भावनाएँ ज़ाहिर करने में झिझक आ सकती है; भावनाएँ सच्ची, आवाज़ धीमी..",
    "Your love-style is sensory and loyal — love means comfort, food, touch and permanence — Venus apne hi sign mein strong hai; pyaar mein aapki instinct par bharosa kiya ja sakta hai..": "आपका प्रेम-अंदाज़ संवेदनशील और वफ़ादार है — प्रेम का मतलब है सुकून, खाना, स्पर्श और स्थायित्व — शुक्र अपनी ही राशि में मज़बूत है; प्यार में आपकी सहज-बुद्धि पर भरोसा किया जा सकता है..",
    "Your love-style is sensory and loyal — love means comfort, food, touch and permanence — Venus combust hai, isliye expression mein hesitation aa sakti hai; feelings genuine, awaaz dheemi..": "आपका प्रेम-अंदाज़ संवेदनशील और वफ़ादार है — प्रेम का मतलब है सुकून, खाना, स्पर्श और स्थायित्व — शुक्र अस्त है, इसलिए इज़हार में थोड़ी हिचकिचाहट आ सकती है; भावनाएँ सच्ची, आवाज़ धीमी..",
    "Your love-style is unconventional and friendship-first — you love minds and freedom — Venus combust hai, isliye expression mein hesitation aa sakti hai; feelings genuine, awaaz dheemi..": "आपका प्रेम-अंदाज़ अलग और दोस्ती-पहले वाला है — आपको दिमाग और आज़ादी पसंद है — शुक्र अस्त है, इसलिए इज़हार में झिझक आ सकती है; भावनाएँ सच्ची, बस आवाज़ धीमी..",
    "Your love-style is unconventional and friendship-first — you love minds and freedom.": "आपका प्रेम-अंदाज़ लीक से हटकर और दोस्ती-पहले वाला है — आप दिमाग़ और आज़ादी से प्रेम करते हैं।",
    "Your marriage timeline": "आपकी शादी की समय-रेखा",
    "a dignified, self-respecting partner, possibly from an established family": "एक सम्मानित, स्वाभिमानी साथी, शायद किसी प्रतिष्ठित परिवार से",
    "a mature, dutiful, patient partner — possibly older or met later": "एक समझदार, कर्तव्यनिष्ठ, धैर्यवान साथी — शायद उम्र में बड़ा या बाद में मिलने वाला",
    "a wise, well-educated, principled partner — often traditional values": "एक समझदार, अच्छी तरह पढ़ा-लिखा, उसूलों वाला साथी — अक्सर पारंपरिक मूल्यों वाला",
    "a younger-feeling, intelligent, talkative partner": "एक कम उम्र-सा लगने वाला, बुद्धिमान, बातूनी पार्टनर",
    "adventurous and idealistic — love must have meaning and room to roam": "साहसी और आदर्शवादी — प्रेम में अर्थ भी हो और घूमने-फिरने की जगह भी",
    "affectionate, harmony-loving partner — romance aur comfort sahaj; marriage karaka apni hi jagah, isliye achha placement": "स्नेही, तालमेल पसंद करने वाला साथी — रोमांस और सुकून सहज; मैरिज कारक अपनी ही जगह, इसलिए अच्छा स्थान",
    "an attractive, artistic, pleasure-loving partner; strong mutual affection": "एक आकर्षक, कलात्मक और सुख-प्रेमी साथी; आपस में गहरा स्नेह।",
    "an emotionally attuned, caring partner; family approval flows easily": "भावनाओं को समझने वाला, ख्याल रखने वाला साथी; परिवार की सहमति आसानी से मिल जाती है",
    "an energetic, protective partner with strong drive": "एक ऊर्जावान, रक्षा करने वाला पार्टनर जिसमें ज़बरदस्त जोश हो",
    "apna time jaan lo.": "अपनी टाइमिंग जान लीजिए।",
    "apne hi sign mein — strong placement": "अपनी ही राशि में — मज़बूत स्थिति",
    "aur": "और",
    "aur karaka se padha jaata hai (upar diya hai), naa ki kisi baithe graha se.": "और कारक से पढ़ा जाता है (ऊपर दिया है), न कि वहाँ बैठे किसी ग्रह से।",
    "average rating": "औसत रेटिंग",
    "axtroshastra.com": "axtroshastra.com",
    "balanced, charming, partnership-minded — marriage matters deeply to them": "संतुलित, आकर्षक, साझेदारी में यकीन रखने वाला — शादी उनके लिए बहुत मायने रखती है",
    "balanced, charming, partnership-minded — marriage matters deeply to them.": "संतुलित, आकर्षक, साझेदारी को अहमियत देने वाले — शादी उनके लिए गहरे मायने रखती है।",
    "batata hai; Navamsa (D9)": "बताता है; नवांश (D9)",
    "bhi kar sakte hain.": "भी कर सकते हैं।",
    "by Cultnuts": "by Cultnuts",
    "by Cultnuts ·": "Cultnuts द्वारा ·",
    "careful and devoted — you love through acts of service and quiet standards": "सतर्क और समर्पित — आप सेवा-भाव और चुपचाप ऊँचे मानकों से प्रेम जताते हैं",
    "caring, family-oriented, emotionally deep — a nurturing presence": "देखभाल करने वाला, परिवार-केंद्रित, भावनात्मक रूप से गहरा — एक पोषण देने वाली मौजूदगी",
    "caring, family-oriented, emotionally deep — a nurturing presence.": "ख़याल रखने वाला, परिवार को अहमियत देने वाला, भावनाओं में गहरा — एक सँभालने वाली मौजूदगी।",
    "communicative, witty, sociable — someone you can talk to for hours": "बातूनी, हाज़िरजवाब, मिलनसार — कोई ऐसा जिससे आप घंटों बात कर सकें",
    "communicative, witty, sociable — someone you can talk to for hours.": "बातूनी, हाज़िरजवाब, मिलनसार — ऐसा कोई जिससे आप घंटों बात कर सकें।",
    "confident, warm, dignified — someone with presence and generosity": "आत्मविश्वासी, गर्मजोश, गरिमामय — जिसमें प्रभावशाली मौजूदगी और उदारता हो",
    "confident, warm, dignified — someone with presence and generosity.": "आत्मविश्वासी, गर्मजोश, गरिमामय — ऐसा कोई जिसमें प्रभाव भी हो और दरियादिली भी।",
    "debilitated — timing par extra dhyaan": "नीच का — टाइमिंग पर खास ध्यान",
    "direct and impulsive in love — you pursue openly and lose interest in games": "प्रेम में सीधे और आवेगपूर्ण — आप खुलकर आगे बढ़ते हैं और खेल-खेल में रुचि खो देते हैं",
    "direct, energetic, quick to decide — someone who takes initiative": "सीधा, ऊर्जावान, जल्दी फैसला लेने वाला — कोई जो पहल करे",
    "direct, energetic, quick to decide — someone who takes initiative.": "सीधे, ऊर्जावान, जल्दी फ़ैसला लेने वाले — कोई जो पहल करे।",
    "diye, isliye grade": "अंक, इसलिए ग्रेड",
    "emotionally attuned, caring partner — ghar-parivar ka warmth bond ka kendra; mood-tuning dono ki saanjhi zimmedari": "भावनाओं को समझने वाला, ख़याल रखने वाला जीवनसाथी — घर-परिवार की गर्माहट इस बंधन का केंद्र है; एक-दूसरे के मूड को समझना दोनों की साझी ज़िम्मेदारी है",
    "energetic, passionate bond — kabhi tez-mizaji bhi (Manglik check upar dekhiye); jhagdon ko jaldi suljhana rishtey ko majboot karta hai": "ऊर्जावान, जोशीला बंधन — कभी-कभी तेज़-मिज़ाज भी (मांगलिक जाँच ऊपर देखिए); झगड़ों को जल्दी सुलझाना रिश्ते को मज़बूत बनाता है",
    "exact marriage windows": "सटीक शादी की विंडो",
    "exalted — best possible dignity": "उच्च — सबसे बेहतरीन स्थिति",
    "gehra par thoda detached bond — partner spiritually-inclined ho sakta hai; over-analysis se bachna, dil se judna": "गहरा पर थोड़ा अलग-सा जुड़ाव — पार्टनर आध्यात्मिक झुकाव वाला हो सकता है; ज़्यादा सोच-विचार से बचें, दिल से जुड़ें",
    "gentle, intuitive, adaptable — emotionally giving and artistic": "कोमल, अंतर्ज्ञानी, ढल जाने वाले — भावनात्मक रूप से देने वाले और कलात्मक।",
    "gentle, intuitive, adaptable — emotionally giving and artistic.": "कोमल, अंतर्ज्ञानी, ढल जाने वाले — भावनात्मक रूप से देने वाले और कलात्मक।",
    "grand and warm-hearted — romance should feel like celebration": "भव्य और गर्मजोश — रोमांस किसी उत्सव जैसा लगना चाहिए",
    "hai — nature, meeting context": "है — स्वभाव, मिलने का संदर्भ",
    "hai.": "है।",
    "harmonising and partnership-built — you are at your best in a committed pair": "सामंजस्यपूर्ण और साझेदारी-केंद्रित — आप एक प्रतिबद्ध जोड़ी में सबसे बेहतर होते हैं",
    "hogi?": "होगी?",
    "independent, idealistic, unconventional — a friend first": "स्वतंत्र, आदर्शवादी, लीक से हटकर — पहले एक दोस्त",
    "independent, idealistic, unconventional — a friend first.": "स्वतंत्र, आदर्शवादी, लीक से हटकर — पहले एक दोस्त।",
    "indications of a dignified, self-respecting partner, possibly from an established family.": "एक सम्मानित, स्वाभिमानी साथी के संकेत, शायद किसी प्रतिष्ठित परिवार से।",
    "indications of a mature, dutiful, patient partner — possibly older or met later.": "एक समझदार, कर्तव्यनिष्ठ, धैर्यवान साथी के संकेत — शायद उम्र में बड़ा या देर से मिलने वाला।",
    "indications of a wise, well-educated, principled partner — often traditional values.": "एक समझदार, अच्छी तरह शिक्षित और उसूलों वाले जीवनसाथी के संकेत — अक्सर पारंपरिक मूल्यों वाले।",
    "indications of a younger-feeling, intelligent, talkative partner.": "एक जवान-सी ऊर्जा वाले, बुद्धिमान और बातूनी साथी के संकेत।",
    "indications of an attractive, artistic, pleasure-loving partner; strong mutual affection.": "एक आकर्षक, कलात्मक और सुख-प्रेमी साथी के संकेत; आपस में गहरा स्नेह।",
    "indications of an emotionally attuned, caring partner; family approval flows easily.": "भावनाओं को समझने वाले, ख्याल रखने वाले साथी के संकेत; परिवार की मंज़ूरी आसानी से मिल जाती है।",
    "indications of an energetic, protective partner with strong drive.": "एक ऊर्जावान, रक्षात्मक और मज़बूत जज़्बे वाले पार्टनर के संकेत।",
    "intense and all-or-nothing — you love deeply or not at all": "गहन और सब-कुछ-या-कुछ-नहीं — आप या तो गहराई से प्रेम करते हैं या बिलकुल नहीं",
    "intense, private, deeply loyal — a bond that runs deep once formed": "गहन, निजी, बेहद वफ़ादार — एक बार बन जाए तो बहुत गहरा उतरने वाला रिश्ता",
    "intense, private, deeply loyal — a bond that runs deep once formed.": "गहन, एकांतप्रिय, गहरे वफ़ादार — एक बार बन जाए तो रिश्ता बहुत गहरा होता है।",
    "kab": "कब",
    "kaisa": "कैसा",
    "ke hisaab se, weak windows mein classical support:": "के हिसाब से, कमज़ोर विंडो में शास्त्रीय सहारा:",
    "kitna pakka": "कितना पक्का",
    "kundli ready hai ✅": "कुंडली तैयार है ✅",
    "logon ko apna exact birth time nahi pata": "लोगों को अपना सही जन्म समय नहीं पता",
    "lord": "स्वामी",
    "marriage typically triggers jab dasha/antardasha lord aapke 7th house ya uske lord se connect hota hai, aur Jupiter ka transit usko confirm karta hai.": "शादी आमतौर पर तब बनती है जब दशा/अंतर्दशा का स्वामी आपके 7वें भाव या उसके स्वामी से जुड़ता है, और गुरु का गोचर उसकी पुष्टि कर देता है।",
    "mature, committed, possibly older ya seriously-minded partner — bond dheere banta hai par tikau; shuruaati sabr baad mein rang laata hai": "परिपक्व, प्रतिबद्ध, शायद उम्र में बड़ा या गंभीर सोच वाला साथी — रिश्ता धीरे बनता है पर टिकाऊ; शुरुआती सब्र बाद में रंग लाता है",
    "mila. Har point ke peeche ek classical rule hai — neeche exact breakdown:": "मिला। हर अंक के पीछे एक शास्त्रीय नियम है — नीचे सटीक ब्यौरा:",
    "nibhega — isiliye classical Jyotish mein shaadi ke liye D9 sabse zaroori divisional chart hai. Aapka D9 lagna": "निभेगा — इसीलिए शास्त्रीय ज्योतिष में शादी के लिए D9 सबसे ज़रूरी विभाजित कुंडली है। आपका D9 लग्न",
    "optimistic, principled, freedom-loving — someone with strong beliefs": "आशावादी, सिद्धांतवादी, आज़ादी पसंद — कोई जिसकी मान्यताएँ मज़बूत हों",
    "optimistic, principled, freedom-loving — someone with strong beliefs.": "आशावादी, उसूलों वाले, आज़ादी पसंद — पक्के विश्वासों वाला कोई इंसान।",
    "partner ka yog": "साथी का योग",
    "planetary data": "ग्रहों का डेटा",
    "playful and verbal — flirting is conversation, and conversation is intimacy": "चंचल और बातूनी — फ़्लर्ट करना यानी बातचीत, और बातचीत ही आत्मीयता है",
    "practical, detail-minded, helpful — someone organised and sincere": "व्यावहारिक, बारीकी पर ध्यान देने वाले, मददगार — कोई व्यवस्थित और सच्चा इंसान",
    "practical, detail-minded, helpful — someone organised and sincere.": "व्यावहारिक, बारीकी पर ध्यान देने वाला, मददगार — कोई व्यवस्थित और सच्चा इंसान।",
    "protective and emotional — you love like family, deep and enveloping": "रक्षात्मक और भावुक — आप परिवार की तरह प्रेम करते हैं, गहरा और समेट लेने वाला",
    "rectify": "रेक्टिफ़ाई",
    "reports generated": "रिपोर्ट बनाई गईं",
    "reserved and enduring — slow to open, near-impossible to shake once committed": "संयमित और टिकाऊ — खुलने में धीमे, पर एक बार प्रतिबद्ध होने के बाद डिगाना लगभग नामुमकिन",
    "responsible, ambitious, mature — often settled or career-established": "ज़िम्मेदार, महत्वाकांक्षी, समझदार — अक्सर सेटल्ड या करियर में जमा हुआ",
    "responsible, ambitious, mature — often settled or career-established.": "ज़िम्मेदार, महत्वाकांक्षी, परिपक्व — अक्सर सेटल्ड या करियर में जमे हुए।",
    "romantic and self-giving — you love like poetry, and must guard against over-giving": "रोमांटिक और समर्पित — आप कविता की तरह प्रेम करते हैं, और ज़रूरत से ज़्यादा दे बैठने से बचना ज़रूरी है",
    "self-respecting, strong-willed partner — individuality rishtey mein central; ek dusre ke ego ko space dena seekhna faydemand": "स्वाभिमानी, दृढ़-इच्छाशक्ति वाला साथी — रिश्ते में हर एक का अपना व्यक्तित्व अहम; एक-दूसरे के अहं को जगह देना सीखना फ़ायदेमंद",
    "sensory and loyal — love means comfort, food, touch and permanence": "इंद्रिय-प्रिय और वफ़ादार — प्रेम यानी आराम, खानपान, स्पर्श और स्थायित्व",
    "sign-numbers houses ke andar": "भावों के अंदर राशि-अंक",
    "steady, comfort-loving, loyal — someone who values stability and family": "स्थिर, आराम पसंद, वफ़ादार — कोई जो स्थिरता और परिवार को महत्व देता हो",
    "steady, comfort-loving, loyal — someone who values stability and family.": "स्थिर, आराम-प्रिय, वफ़ादार — जो स्थिरता और परिवार को अहमियत देता है।",
    "support@axtroshastra.com": "support@axtroshastra.com",
    "to your result": "आपके नतीजे तक",
    "unconventional and friendship-first — you love minds and freedom": "अपरंपरागत और दोस्ती-पहले — आप दिमाग़ और आज़ादी से प्रेम करते हैं",
    "unconventional attraction — partner alag background/community/desh se ho sakta hai; shuruaat sudden ya intense": "अनोखा आकर्षण — साथी अलग पृष्ठभूमि/समुदाय/देश से हो सकता है; शुरुआत अचानक या तीव्र",
    "whole-sign houses.": "पूर्ण-राशि भाव पद्धति।",
    "wise, principled, often traditional-values partner — 7th house mein Guru ko classical texts shubh maante hain; family-approved yog": "समझदार, सिद्धांतवादी, अक्सर पारंपरिक मूल्यों वाला साथी — 7वें भाव में गुरु को शास्त्र शुभ मानते हैं; परिवार की पसंद वाला योग",
    "yeh partnership ke rang ko sabse seedha shape dete hain:": "ये साझेदारी के रंग को सबसे सीधे आकार देते हैं:",
    "youthful, communicative partner — baat-cheet aapka asli gum hai; aksar partner young-natured ya age-gap kam": "युवा, बातचीत करने वाला साथी — बातचीत ही आपकी असली जोड़ने वाली कड़ी है; अक्सर साथी युवा स्वभाव का या उम्र का फ़र्क कम",
    "±15 minute ka difference windows ko months tak shift kar sakta hai. Doosri websites 12:00 baje assume karke galat report de deti hain. Hum aapke approximate time ke saath kaam karte hain — aur agar aap chahein toh life events se aapka time": "±15 मिनट का फ़र्क विंडो को महीनों तक खिसका सकता है। दूसरी वेबसाइटें 12:00 दोपहर मान लेती हैं और आपको ग़लत रिपोर्ट दे देती हैं। हम आपके अनुमानित समय के साथ काम करते हैं — और अगर आप चाहें तो आपके जीवन की घटनाओं से आपका समय",
    "· Computational Vedic Astrology": "· कंप्यूटेशनल वैदिक ज्योतिष",
    "· Instant Delivery": "· तुरंत डिलीवरी",
    "· support@axtroshastra.com": "· support@axtroshastra.com",
    "आपका नक्षत्र: अनुराधा (Lotus)": "आपका नक्षत्र: अनुराधा (Lotus)",
    "आपका नक्षत्र: अश्विनी (Horse's head)": "आपका नक्षत्र: अश्विनी (Horse's head)",
    "आपका नक्षत्र: आर्द्रा (Teardrop / gem)": "आपका नक्षत्र: आर्द्रा (आँसू की बूँद / रत्न)",
    "आपका नक्षत्र: आश्लेषा (Coiled serpent)": "आपका नक्षत्र: आश्लेषा (Coiled serpent)",
    "आपका नक्षत्र: उत्तर आषाढ़ा (Elephant tusk / cot)": "आपका नक्षत्र: उत्तर आषाढ़ा (Elephant tusk / cot)",
    "आपका नक्षत्र: उत्तर फाल्गुनी (Back of the bed)": "आपका नक्षत्र: उत्तर फाल्गुनी (Back of the bed)",
    "आपका नक्षत्र: उत्तर भाद्रपद (Twins / serpent of the deep)": "आपका नक्षत्र: उत्तर भाद्रपद (Twins / serpent of the deep)",
    "आपका नक्षत्र: कृत्तिका (Razor / flame)": "आपका नक्षत्र: कृत्तिका (Razor / flame)",
    "आपका नक्षत्र: चित्रा (Pearl / jewel)": "आपका नक्षत्र: चित्रा (Pearl / jewel)",
    "आपका नक्षत्र: ज्येष्ठा (Earring / umbrella)": "आपका नक्षत्र: ज्येष्ठा (Earring / umbrella)",
    "आपका नक्षत्र: धनिष्ठा (Drum)": "आपका नक्षत्र: धनिष्ठा (Drum)",
    "आपका नक्षत्र: पुनर्वसु (Bow and quiver)": "आपका नक्षत्र: पुनर्वसु (Bow and quiver)",
    "आपका नक्षत्र: पुष्य (Flower / udder)": "आपका नक्षत्र: पुष्य (Flower / udder)",
    "आपका नक्षत्र: पूर्व आषाढ़ा (Elephant tusk / fan)": "आपका नक्षत्र: पूर्व आषाढ़ा (Elephant tusk / fan)",
    "आपका नक्षत्र: पूर्व फाल्गुनी (Front of the bed)": "आपका नक्षत्र: पूर्व फाल्गुनी (Front of the bed)",
    "आपका नक्षत्र: पूर्व भाद्रपद (Sword / two-faced man)": "आपका नक्षत्र: पूर्व भाद्रपद (Sword / two-faced man)",
    "आपका नक्षत्र: भरणी (Yoni)": "आपका नक्षत्र: भरणी (Yoni)",
    "आपका नक्षत्र: मघा (Throne)": "आपका नक्षत्र: मघा (Throne)",
    "आपका नक्षत्र: मूल (Bundle of roots)": "आपका नक्षत्र: मूल (Bundle of roots)",
    "आपका नक्षत्र: मृगशिरा (Deer's head)": "आपका नक्षत्र: मृगशिरा (Deer's head)",
    "आपका नक्षत्र: रेवती (Fish / drum)": "आपका नक्षत्र: रेवती (Fish / drum)",
    "आपका नक्षत्र: रोहिणी (Chariot / ox-cart)": "आपका नक्षत्र: रोहिणी (Chariot / ox-cart)",
    "आपका नक्षत्र: विशाखा (Triumphal archway)": "आपका नक्षत्र: विशाखा (Triumphal archway)",
    "आपका नक्षत्र: शतभिषा (Empty circle / 100 healers)": "आपका नक्षत्र: शतभिषा (Empty circle / 100 healers)",
    "आपका नक्षत्र: श्रवण (Ear / three footprints)": "आपका नक्षत्र: श्रवण (Ear / three footprints)",
    "आपका नक्षत्र: स्वाति (Young sprout in wind)": "आपका नक्षत्र: स्वाति (Young sprout in wind)",
    "आपका नक्षत्र: हस्त (Hand)": "आपका नक्षत्र: हस्त (Hand)",
    "— Aarav, 27": "— आरव, 27",
    "— Divya, 29": "— Divya, 29",
    "— Karthik, 30": "— Karthik, 30",
    "— Rahul, 32": "— Rahul, 32",
    "— Sneha, 28": "— स्नेहा, 28",
    "— aur cancellation check (most charts mein cancellation hota hai)": "— और एक कैंसलेशन जाँच (ज़्यादातर कुंडलियों में कैंसलेशन होता है)",
    "— har window mein kya karna chahiye": "— हर विंडो में क्या करना चाहिए",
    "— kab rishtey aayenge par banenge nahi, aur kyun": "— कब रिश्ते आएँगे पर बनेंगे नहीं, और क्यों",
    "— koi graha 7th mein nahi. Yeh normal aur aksar shubh maana jaata hai: partner ka pattern 7th ke": "— 7वें भाव में कोई ग्रह नहीं। यह सामान्य और अक्सर शुभ माना जाता है: पार्टनर का पैटर्न 7वें भाव के",
    "— peak (dusra charan), till": "— चरम (दूसरा चरण), तक",
    "— rising (pehla charan), till": "— उदय (पहला चरण), तक",
    "— setting (aakhri charan), till": "— अस्त होते हुए (आख़िरी चरण), तक",
    "— साल aur months, with strength grade": "— साल और महीने, मज़बूती ग्रेड के साथ",
    "← swipe, or hover to pause →": "← स्वाइप करें, या रोकने के लिए हॉवर करें →",
    "⚙️ IIT–IIM ALUMNI BUILT": "⚙️ IIT–IIM एलुमनाई द्वारा बनाया गया",
    "✦ AXTROSHASTRA": "✦ AXTROSHASTRA",
    "⭐ Aapka current dasha period directly relevant hai aapke marriage timing se.": "⭐ आपकी मौजूदा दशा का दौर सीधे तौर पर आपकी शादी के समय से जुड़ा है।",
}
